# Makefile.in generated by automake 1.11.1 from Makefile.am.
# Makefile.  Generated from Makefile.in by configure.

# Copyright (C) 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002,
# 2003, 2004, 2005, 2006, 2007, 2008, 2009  Free Software Foundation,
# Inc.
# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.




pkgdatadir = $(datadir)/pktanon
pkgincludedir = $(includedir)/pktanon
pkglibdir = $(libdir)/pktanon
pkglibexecdir = $(libexecdir)/pktanon
am__cd = CDPATH="$${ZSH_VERSION+.}$(PATH_SEPARATOR)" && cd
install_sh_DATA = $(install_sh) -c -m 644
install_sh_PROGRAM = $(install_sh) -c
install_sh_SCRIPT = $(install_sh) -c
INSTALL_HEADER = $(INSTALL_DATA)
transform = $(program_transform_name)
NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
bin_PROGRAMS = pktanon$(EXEEXT)
subdir = .
DIST_COMMON = README $(am__configure_deps) $(srcdir)/Makefile.am \
	$(srcdir)/Makefile.in $(top_srcdir)/configure AUTHORS COPYING \
	ChangeLog INSTALL NEWS TODO depcomp install-sh missing
ACLOCAL_M4 = $(top_srcdir)/aclocal.m4
am__aclocal_m4_deps = $(top_srcdir)/configure.ac
am__configure_deps = $(am__aclocal_m4_deps) $(CONFIGURE_DEPENDENCIES) \
	$(ACLOCAL_M4)
am__CONFIG_DISTCLEAN_FILES = config.status config.cache config.log \
 configure.lineno config.status.lineno
mkinstalldirs = $(install_sh) -d
CONFIG_CLEAN_FILES =
CONFIG_CLEAN_VPATH_FILES =
am__installdirs = "$(DESTDIR)$(bindir)"
PROGRAMS = $(bin_PROGRAMS)
am_pktanon_OBJECTS = main.$(OBJEXT) Configuration.$(OBJEXT) \
	triggerconf.$(OBJEXT) PcapFile.$(OBJEXT) \
	RandomNumberGenerator.$(OBJEXT) StatisticEngine.$(OBJEXT) \
	Stream.$(OBJEXT) BufferedFile.$(OBJEXT) Transformer.$(OBJEXT) \
	Timer.$(OBJEXT) Utils.$(OBJEXT) ArpPacket.$(OBJEXT) \
	EthernetPacket.$(OBJEXT) Frame.$(OBJEXT) IcmpPacket.$(OBJEXT) \
	IpPacket.$(OBJEXT) Ipv6Packet.$(OBJEXT) Packet.$(OBJEXT) \
	PayloadPacket.$(OBJEXT) TcpPacket.$(OBJEXT) \
	UdpPacket.$(OBJEXT) PacketFactory.$(OBJEXT) \
	VlanPacket.$(OBJEXT) sha1.$(OBJEXT) sha1_hmac.$(OBJEXT) \
	rijndael.$(OBJEXT) panonymizer.$(OBJEXT) \
	AnonBroadcastHandler.$(OBJEXT) AnonBytewise.$(OBJEXT) \
	AnonBytewiseHashHmacSha1.$(OBJEXT) \
	AnonBytewiseHashSha1.$(OBJEXT) AnonConstOverwrite.$(OBJEXT) \
	AnonContinuousChar.$(OBJEXT) AnonFactory.$(OBJEXT) \
	AnonHashHmacSha1.$(OBJEXT) AnonHashSha1.$(OBJEXT) \
	AnonIdentity.$(OBJEXT) AnonPrimitive.$(OBJEXT) \
	AnonRandomize.$(OBJEXT) AnonShorten.$(OBJEXT) \
	AnonShuffle.$(OBJEXT) AnonWhitenoise.$(OBJEXT) \
	AnonCryptoPan.$(OBJEXT)
pktanon_OBJECTS = $(am_pktanon_OBJECTS)
pktanon_LDADD = $(LDADD)
DEFAULT_INCLUDES = -I.
depcomp = $(SHELL) $(top_srcdir)/depcomp
am__depfiles_maybe = depfiles
am__mv = mv -f
CXXCOMPILE = $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) \
	$(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS)
CXXLD = $(CXX)
CXXLINK = $(CXXLD) $(AM_CXXFLAGS) $(CXXFLAGS) $(AM_LDFLAGS) $(LDFLAGS) \
	-o $@
COMPILE = $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) \
	$(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
CCLD = $(CC)
LINK = $(CCLD) $(AM_CFLAGS) $(CFLAGS) $(AM_LDFLAGS) $(LDFLAGS) -o $@
SOURCES = $(pktanon_SOURCES)
DIST_SOURCES = $(pktanon_SOURCES)
ETAGS = etags
CTAGS = ctags
DISTFILES = $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST)
distdir = $(PACKAGE)-$(VERSION)
top_distdir = $(distdir)
am__remove_distdir = \
  { test ! -d "$(distdir)" \
    || { find "$(distdir)" -type d ! -perm -200 -exec chmod u+w {} ';' \
         && rm -fr "$(distdir)"; }; }
DIST_ARCHIVES = $(distdir).tar.gz
GZIP_ENV = --best
distuninstallcheck_listfiles = find . -type f -print
distcleancheck_listfiles = find . -type f -print
ACLOCAL = ${SHELL} /home/pi/projects/pktanon/missing --run aclocal-1.11
AMTAR = ${SHELL} /home/pi/projects/pktanon/missing --run tar
AUTOCONF = ${SHELL} /home/pi/projects/pktanon/missing --run autoconf
AUTOHEADER = ${SHELL} /home/pi/projects/pktanon/missing --run autoheader
AUTOMAKE = ${SHELL} /home/pi/projects/pktanon/missing --run automake-1.11
AWK = mawk
CC = gcc
CCDEPMODE = depmode=gcc3
CFLAGS = -g -O2
CPPFLAGS = 
CXX = g++
CXXCPP = g++ -E
CXXDEPMODE = depmode=gcc3
CXXFLAGS = -g -O2
CYGPATH_W = echo
DEFS = -DPACKAGE_NAME=\"pktanon\" -DPACKAGE_TARNAME=\"pktanon\" -DPACKAGE_VERSION=\"1.4.0-dev\" -DPACKAGE_STRING=\"pktanon\ 1.4.0-dev\" -DPACKAGE_BUGREPORT=\"www.tm.kit.edu/pktanon\" -DPACKAGE_URL=\"\" -DPACKAGE=\"pktanon\" -DVERSION=\"1.4.0-dev\" -DHAVE_LIBXERCES_C=1 -DHAVE_LIBPTHREAD=1 -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1
DEPDIR = .deps
ECHO_C = 
ECHO_N = -n
ECHO_T = 
EGREP = /bin/grep -E
EXEEXT = 
GREP = /bin/grep
INSTALL = /usr/bin/install -c
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_PROGRAM = ${INSTALL}
INSTALL_SCRIPT = ${INSTALL}
INSTALL_STRIP_PROGRAM = $(install_sh) -c -s
LDFLAGS = 
LIBOBJS = 
LIBS = -lpthread -lxerces-c 
LTLIBOBJS = 
MAKEINFO = ${SHELL} /home/pi/projects/pktanon/missing --run makeinfo
MKDIR_P = /bin/mkdir -p
OBJEXT = o
PACKAGE = pktanon
PACKAGE_BUGREPORT = www.tm.kit.edu/pktanon
PACKAGE_NAME = pktanon
PACKAGE_STRING = pktanon 1.4.0-dev
PACKAGE_TARNAME = pktanon
PACKAGE_URL = 
PACKAGE_VERSION = 1.4.0-dev
PATH_SEPARATOR = :
SET_MAKE = 
SHELL = /bin/bash
STRIP = 
VERSION = 1.4.0-dev
abs_builddir = /home/pi/projects/pktanon
abs_srcdir = /home/pi/projects/pktanon
abs_top_builddir = /home/pi/projects/pktanon
abs_top_srcdir = /home/pi/projects/pktanon
ac_ct_CC = gcc
ac_ct_CXX = g++
am__include = include
am__leading_dot = .
am__quote = 
am__tar = ${AMTAR} chof - "$$tardir"
am__untar = ${AMTAR} xf -
bindir = ${exec_prefix}/bin
build_alias = 
builddir = .
datadir = ${datarootdir}
datarootdir = ${prefix}/share
docdir = ${datarootdir}/doc/${PACKAGE_TARNAME}
dvidir = ${docdir}
exec_prefix = ${prefix}
host_alias = 
htmldir = ${docdir}
includedir = ${prefix}/include
infodir = ${datarootdir}/info
install_sh = ${SHELL} /home/pi/projects/pktanon/install-sh
libdir = ${exec_prefix}/lib
libexecdir = ${exec_prefix}/libexec
localedir = ${datarootdir}/locale
localstatedir = ${prefix}/var
mandir = ${datarootdir}/man
mkdir_p = /bin/mkdir -p
oldincludedir = /usr/include
pdfdir = ${docdir}
prefix = /usr/local
program_transform_name = s,x,x,
psdir = ${docdir}
sbindir = ${exec_prefix}/sbin
sharedstatedir = ${prefix}/com
srcdir = .
sysconfdir = ${prefix}/etc
target_alias = 
top_build_prefix = 
top_builddir = .
top_srcdir = .
AM_CPPFLAGS = -DLINUX -D_LINUX -Isrc -D_REENTRANT -D_FILE_OFFSET_BITS=64 -pthread
AM_LDFLAGS = -lpthread -lxerces-c 
EXTRA_DIST = profiles/*.xml

#pktanon_SOURCES += \
#  src/benchmark/AnonPrimitiveBenchmark.cpp \
#  src/benchmark/AnonPrimitiveBenchmark.h

#pktanon_SOURCES += \
#  src/anonprimitives/patricia/Patricia.cpp \
#  src/anonprimitives/patricia/Patricia.h
pktanon_SOURCES = src/main.cpp src/Configuration.cpp \
	src/Configuration.h src/triggerconf.cpp src/triggerconf.h \
	src/PcapFile.cpp src/PcapFile.h src/RandomNumberGenerator.cpp \
	src/RandomNumberGenerator.h src/StatisticEngine.cpp \
	src/StatisticEngine.h src/Stream.cpp src/Stream.h \
	src/BufferedFile.cpp src/BufferedFile.h src/Transformer.cpp \
	src/Transformer.h src/Timer.cpp src/Timer.h src/Utils.cpp \
	src/Utils.h src/packets/ArpPacket.cpp src/packets/ArpPacket.h \
	src/packets/EthernetPacket.cpp src/packets/EthernetPacket.h \
	src/packets/Frame.cpp src/packets/Frame.h \
	src/packets/IcmpPacket.cpp src/packets/IcmpPacket.h \
	src/packets/IpPacket.cpp src/packets/IpPacket.h \
	src/packets/Ipv6Packet.cpp src/packets/Ipv6Packet.h \
	src/packets/Packet.cpp src/packets/Packet.h \
	src/packets/PayloadPacket.cpp src/packets/PayloadPacket.h \
	src/packets/TcpPacket.cpp src/packets/TcpPacket.h \
	src/packets/UdpPacket.cpp src/packets/UdpPacket.h \
	src/packets/PacketFactory.cpp src/packets/PacketFactory.h \
	src/packets/VlanPacket.cpp src/packets/VlanPacket.h \
	src/anonprimitives/hmacsha1/sha1.cpp \
	src/anonprimitives/hmacsha1/sha1.h \
	src/anonprimitives/hmacsha1/sha1_hmac.cpp \
	src/anonprimitives/hmacsha1/sha1_hmac.h \
	src/anonprimitives/cryptopan/rijndael.cpp \
	src/anonprimitives/cryptopan/rijndael.h \
	src/anonprimitives/cryptopan/panonymizer.cpp \
	src/anonprimitives/cryptopan/panonymizer.h \
	src/anonprimitives/AnonBroadcastHandler.cpp \
	src/anonprimitives/AnonBroadcastHandler.h \
	src/anonprimitives/AnonBytewise.cpp \
	src/anonprimitives/AnonBytewise.h \
	src/anonprimitives/AnonBytewiseHashHmacSha1.cpp \
	src/anonprimitives/AnonBytewiseHashHmacSha1.h \
	src/anonprimitives/AnonBytewiseHashSha1.cpp \
	src/anonprimitives/AnonBytewiseHashSha1.h \
	src/anonprimitives/AnonConstOverwrite.cpp \
	src/anonprimitives/AnonConstOverwrite.h \
	src/anonprimitives/AnonContinuousChar.cpp \
	src/anonprimitives/AnonContinuousChar.h \
	src/anonprimitives/AnonFactory.cpp \
	src/anonprimitives/AnonFactory.h \
	src/anonprimitives/AnonHashHmacSha1.cpp \
	src/anonprimitives/AnonHashHmacSha1.h \
	src/anonprimitives/AnonHashSha1.cpp \
	src/anonprimitives/AnonHashSha1.h \
	src/anonprimitives/AnonIdentity.cpp \
	src/anonprimitives/AnonIdentity.h \
	src/anonprimitives/AnonPrimitive.cpp \
	src/anonprimitives/AnonPrimitive.h \
	src/anonprimitives/AnonRandomize.cpp \
	src/anonprimitives/AnonRandomize.h \
	src/anonprimitives/AnonShorten.cpp \
	src/anonprimitives/AnonShorten.h \
	src/anonprimitives/AnonShuffle.cpp \
	src/anonprimitives/AnonShuffle.h \
	src/anonprimitives/AnonWhitenoise.cpp \
	src/anonprimitives/AnonWhitenoise.h \
	src/anonprimitives/AnonCryptoPan.cpp \
	src/anonprimitives/AnonCryptoPan.h
all: all-am

.SUFFIXES:
.SUFFIXES: .cpp .o .obj
am--refresh:
	@:
$(srcdir)/Makefile.in:  $(srcdir)/Makefile.am  $(am__configure_deps)
	@for dep in $?; do \
	  case '$(am__configure_deps)' in \
	    *$$dep*) \
	      echo ' cd $(srcdir) && $(AUTOMAKE) --gnu'; \
	      $(am__cd) $(srcdir) && $(AUTOMAKE) --gnu \
		&& exit 0; \
	      exit 1;; \
	  esac; \
	done; \
	echo ' cd $(top_srcdir) && $(AUTOMAKE) --gnu Makefile'; \
	$(am__cd) $(top_srcdir) && \
	  $(AUTOMAKE) --gnu Makefile
.PRECIOUS: Makefile
Makefile: $(srcdir)/Makefile.in $(top_builddir)/config.status
	@case '$?' in \
	  *config.status*) \
	    echo ' $(SHELL) ./config.status'; \
	    $(SHELL) ./config.status;; \
	  *) \
	    echo ' cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__depfiles_maybe)'; \
	    cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__depfiles_maybe);; \
	esac;

$(top_builddir)/config.status: $(top_srcdir)/configure $(CONFIG_STATUS_DEPENDENCIES)
	$(SHELL) ./config.status --recheck

$(top_srcdir)/configure:  $(am__configure_deps)
	$(am__cd) $(srcdir) && $(AUTOCONF)
$(ACLOCAL_M4):  $(am__aclocal_m4_deps)
	$(am__cd) $(srcdir) && $(ACLOCAL) $(ACLOCAL_AMFLAGS)
$(am__aclocal_m4_deps):
install-binPROGRAMS: $(bin_PROGRAMS)
	@$(NORMAL_INSTALL)
	test -z "$(bindir)" || $(MKDIR_P) "$(DESTDIR)$(bindir)"
	@list='$(bin_PROGRAMS)'; test -n "$(bindir)" || list=; \
	for p in $$list; do echo "$$p $$p"; done | \
	sed 's/$(EXEEXT)$$//' | \
	while read p p1; do if test -f $$p; \
	  then echo "$$p"; echo "$$p"; else :; fi; \
	done | \
	sed -e 'p;s,.*/,,;n;h' -e 's|.*|.|' \
	    -e 'p;x;s,.*/,,;s/$(EXEEXT)$$//;$(transform);s/$$/$(EXEEXT)/' | \
	sed 'N;N;N;s,\n, ,g' | \
	$(AWK) 'BEGIN { files["."] = ""; dirs["."] = 1 } \
	  { d=$$3; if (dirs[d] != 1) { print "d", d; dirs[d] = 1 } \
	    if ($$2 == $$4) files[d] = files[d] " " $$1; \
	    else { print "f", $$3 "/" $$4, $$1; } } \
	  END { for (d in files) print "f", d, files[d] }' | \
	while read type dir files; do \
	    if test "$$dir" = .; then dir=; else dir=/$$dir; fi; \
	    test -z "$$files" || { \
	      echo " $(INSTALL_PROGRAM_ENV) $(INSTALL_PROGRAM) $$files '$(DESTDIR)$(bindir)$$dir'"; \
	      $(INSTALL_PROGRAM_ENV) $(INSTALL_PROGRAM) $$files "$(DESTDIR)$(bindir)$$dir" || exit $$?; \
	    } \
	; done

uninstall-binPROGRAMS:
	@$(NORMAL_UNINSTALL)
	@list='$(bin_PROGRAMS)'; test -n "$(bindir)" || list=; \
	files=`for p in $$list; do echo "$$p"; done | \
	  sed -e 'h;s,^.*/,,;s/$(EXEEXT)$$//;$(transform)' \
	      -e 's/$$/$(EXEEXT)/' `; \
	test -n "$$list" || exit 0; \
	echo " ( cd '$(DESTDIR)$(bindir)' && rm -f" $$files ")"; \
	cd "$(DESTDIR)$(bindir)" && rm -f $$files

clean-binPROGRAMS:
	-test -z "$(bin_PROGRAMS)" || rm -f $(bin_PROGRAMS)
pktanon$(EXEEXT): $(pktanon_OBJECTS) $(pktanon_DEPENDENCIES) 
	@rm -f pktanon$(EXEEXT)
	$(CXXLINK) $(pktanon_OBJECTS) $(pktanon_LDADD) $(LIBS)

mostlyclean-compile:
	-rm -f *.$(OBJEXT)

distclean-compile:
	-rm -f *.tab.c

include ./$(DEPDIR)/AnonBroadcastHandler.Po
include ./$(DEPDIR)/AnonBytewise.Po
include ./$(DEPDIR)/AnonBytewiseHashHmacSha1.Po
include ./$(DEPDIR)/AnonBytewiseHashSha1.Po
include ./$(DEPDIR)/AnonConstOverwrite.Po
include ./$(DEPDIR)/AnonContinuousChar.Po
include ./$(DEPDIR)/AnonCryptoPan.Po
include ./$(DEPDIR)/AnonFactory.Po
include ./$(DEPDIR)/AnonHashHmacSha1.Po
include ./$(DEPDIR)/AnonHashSha1.Po
include ./$(DEPDIR)/AnonIdentity.Po
include ./$(DEPDIR)/AnonPrimitive.Po
include ./$(DEPDIR)/AnonRandomize.Po
include ./$(DEPDIR)/AnonShorten.Po
include ./$(DEPDIR)/AnonShuffle.Po
include ./$(DEPDIR)/AnonWhitenoise.Po
include ./$(DEPDIR)/ArpPacket.Po
include ./$(DEPDIR)/BufferedFile.Po
include ./$(DEPDIR)/Configuration.Po
include ./$(DEPDIR)/EthernetPacket.Po
include ./$(DEPDIR)/Frame.Po
include ./$(DEPDIR)/IcmpPacket.Po
include ./$(DEPDIR)/IpPacket.Po
include ./$(DEPDIR)/Ipv6Packet.Po
include ./$(DEPDIR)/Packet.Po
include ./$(DEPDIR)/PacketFactory.Po
include ./$(DEPDIR)/PayloadPacket.Po
include ./$(DEPDIR)/PcapFile.Po
include ./$(DEPDIR)/RandomNumberGenerator.Po
include ./$(DEPDIR)/StatisticEngine.Po
include ./$(DEPDIR)/Stream.Po
include ./$(DEPDIR)/TcpPacket.Po
include ./$(DEPDIR)/Timer.Po
include ./$(DEPDIR)/Transformer.Po
include ./$(DEPDIR)/UdpPacket.Po
include ./$(DEPDIR)/Utils.Po
include ./$(DEPDIR)/VlanPacket.Po
include ./$(DEPDIR)/main.Po
include ./$(DEPDIR)/panonymizer.Po
include ./$(DEPDIR)/rijndael.Po
include ./$(DEPDIR)/sha1.Po
include ./$(DEPDIR)/sha1_hmac.Po
include ./$(DEPDIR)/triggerconf.Po

.cpp.o:
	$(CXXCOMPILE) -MT $@ -MD -MP -MF $(DEPDIR)/$*.Tpo -c -o $@ $<
	$(am__mv) $(DEPDIR)/$*.Tpo $(DEPDIR)/$*.Po
#	source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXXCOMPILE) -c -o $@ $<

.cpp.obj:
	$(CXXCOMPILE) -MT $@ -MD -MP -MF $(DEPDIR)/$*.Tpo -c -o $@ `$(CYGPATH_W) '$<'`
	$(am__mv) $(DEPDIR)/$*.Tpo $(DEPDIR)/$*.Po
#	source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXXCOMPILE) -c -o $@ `$(CYGPATH_W) '$<'`

main.o: src/main.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT main.o -MD -MP -MF $(DEPDIR)/main.Tpo -c -o main.o `test -f 'src/main.cpp' || echo '$(srcdir)/'`src/main.cpp
	$(am__mv) $(DEPDIR)/main.Tpo $(DEPDIR)/main.Po
#	source='src/main.cpp' object='main.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o main.o `test -f 'src/main.cpp' || echo '$(srcdir)/'`src/main.cpp

main.obj: src/main.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT main.obj -MD -MP -MF $(DEPDIR)/main.Tpo -c -o main.obj `if test -f 'src/main.cpp'; then $(CYGPATH_W) 'src/main.cpp'; else $(CYGPATH_W) '$(srcdir)/src/main.cpp'; fi`
	$(am__mv) $(DEPDIR)/main.Tpo $(DEPDIR)/main.Po
#	source='src/main.cpp' object='main.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o main.obj `if test -f 'src/main.cpp'; then $(CYGPATH_W) 'src/main.cpp'; else $(CYGPATH_W) '$(srcdir)/src/main.cpp'; fi`

Configuration.o: src/Configuration.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT Configuration.o -MD -MP -MF $(DEPDIR)/Configuration.Tpo -c -o Configuration.o `test -f 'src/Configuration.cpp' || echo '$(srcdir)/'`src/Configuration.cpp
	$(am__mv) $(DEPDIR)/Configuration.Tpo $(DEPDIR)/Configuration.Po
#	source='src/Configuration.cpp' object='Configuration.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o Configuration.o `test -f 'src/Configuration.cpp' || echo '$(srcdir)/'`src/Configuration.cpp

Configuration.obj: src/Configuration.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT Configuration.obj -MD -MP -MF $(DEPDIR)/Configuration.Tpo -c -o Configuration.obj `if test -f 'src/Configuration.cpp'; then $(CYGPATH_W) 'src/Configuration.cpp'; else $(CYGPATH_W) '$(srcdir)/src/Configuration.cpp'; fi`
	$(am__mv) $(DEPDIR)/Configuration.Tpo $(DEPDIR)/Configuration.Po
#	source='src/Configuration.cpp' object='Configuration.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o Configuration.obj `if test -f 'src/Configuration.cpp'; then $(CYGPATH_W) 'src/Configuration.cpp'; else $(CYGPATH_W) '$(srcdir)/src/Configuration.cpp'; fi`

triggerconf.o: src/triggerconf.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT triggerconf.o -MD -MP -MF $(DEPDIR)/triggerconf.Tpo -c -o triggerconf.o `test -f 'src/triggerconf.cpp' || echo '$(srcdir)/'`src/triggerconf.cpp
	$(am__mv) $(DEPDIR)/triggerconf.Tpo $(DEPDIR)/triggerconf.Po
#	source='src/triggerconf.cpp' object='triggerconf.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o triggerconf.o `test -f 'src/triggerconf.cpp' || echo '$(srcdir)/'`src/triggerconf.cpp

triggerconf.obj: src/triggerconf.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT triggerconf.obj -MD -MP -MF $(DEPDIR)/triggerconf.Tpo -c -o triggerconf.obj `if test -f 'src/triggerconf.cpp'; then $(CYGPATH_W) 'src/triggerconf.cpp'; else $(CYGPATH_W) '$(srcdir)/src/triggerconf.cpp'; fi`
	$(am__mv) $(DEPDIR)/triggerconf.Tpo $(DEPDIR)/triggerconf.Po
#	source='src/triggerconf.cpp' object='triggerconf.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o triggerconf.obj `if test -f 'src/triggerconf.cpp'; then $(CYGPATH_W) 'src/triggerconf.cpp'; else $(CYGPATH_W) '$(srcdir)/src/triggerconf.cpp'; fi`

PcapFile.o: src/PcapFile.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT PcapFile.o -MD -MP -MF $(DEPDIR)/PcapFile.Tpo -c -o PcapFile.o `test -f 'src/PcapFile.cpp' || echo '$(srcdir)/'`src/PcapFile.cpp
	$(am__mv) $(DEPDIR)/PcapFile.Tpo $(DEPDIR)/PcapFile.Po
#	source='src/PcapFile.cpp' object='PcapFile.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o PcapFile.o `test -f 'src/PcapFile.cpp' || echo '$(srcdir)/'`src/PcapFile.cpp

PcapFile.obj: src/PcapFile.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT PcapFile.obj -MD -MP -MF $(DEPDIR)/PcapFile.Tpo -c -o PcapFile.obj `if test -f 'src/PcapFile.cpp'; then $(CYGPATH_W) 'src/PcapFile.cpp'; else $(CYGPATH_W) '$(srcdir)/src/PcapFile.cpp'; fi`
	$(am__mv) $(DEPDIR)/PcapFile.Tpo $(DEPDIR)/PcapFile.Po
#	source='src/PcapFile.cpp' object='PcapFile.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o PcapFile.obj `if test -f 'src/PcapFile.cpp'; then $(CYGPATH_W) 'src/PcapFile.cpp'; else $(CYGPATH_W) '$(srcdir)/src/PcapFile.cpp'; fi`

RandomNumberGenerator.o: src/RandomNumberGenerator.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT RandomNumberGenerator.o -MD -MP -MF $(DEPDIR)/RandomNumberGenerator.Tpo -c -o RandomNumberGenerator.o `test -f 'src/RandomNumberGenerator.cpp' || echo '$(srcdir)/'`src/RandomNumberGenerator.cpp
	$(am__mv) $(DEPDIR)/RandomNumberGenerator.Tpo $(DEPDIR)/RandomNumberGenerator.Po
#	source='src/RandomNumberGenerator.cpp' object='RandomNumberGenerator.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o RandomNumberGenerator.o `test -f 'src/RandomNumberGenerator.cpp' || echo '$(srcdir)/'`src/RandomNumberGenerator.cpp

RandomNumberGenerator.obj: src/RandomNumberGenerator.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT RandomNumberGenerator.obj -MD -MP -MF $(DEPDIR)/RandomNumberGenerator.Tpo -c -o RandomNumberGenerator.obj `if test -f 'src/RandomNumberGenerator.cpp'; then $(CYGPATH_W) 'src/RandomNumberGenerator.cpp'; else $(CYGPATH_W) '$(srcdir)/src/RandomNumberGenerator.cpp'; fi`
	$(am__mv) $(DEPDIR)/RandomNumberGenerator.Tpo $(DEPDIR)/RandomNumberGenerator.Po
#	source='src/RandomNumberGenerator.cpp' object='RandomNumberGenerator.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o RandomNumberGenerator.obj `if test -f 'src/RandomNumberGenerator.cpp'; then $(CYGPATH_W) 'src/RandomNumberGenerator.cpp'; else $(CYGPATH_W) '$(srcdir)/src/RandomNumberGenerator.cpp'; fi`

StatisticEngine.o: src/StatisticEngine.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT StatisticEngine.o -MD -MP -MF $(DEPDIR)/StatisticEngine.Tpo -c -o StatisticEngine.o `test -f 'src/StatisticEngine.cpp' || echo '$(srcdir)/'`src/StatisticEngine.cpp
	$(am__mv) $(DEPDIR)/StatisticEngine.Tpo $(DEPDIR)/StatisticEngine.Po
#	source='src/StatisticEngine.cpp' object='StatisticEngine.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o StatisticEngine.o `test -f 'src/StatisticEngine.cpp' || echo '$(srcdir)/'`src/StatisticEngine.cpp

StatisticEngine.obj: src/StatisticEngine.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT StatisticEngine.obj -MD -MP -MF $(DEPDIR)/StatisticEngine.Tpo -c -o StatisticEngine.obj `if test -f 'src/StatisticEngine.cpp'; then $(CYGPATH_W) 'src/StatisticEngine.cpp'; else $(CYGPATH_W) '$(srcdir)/src/StatisticEngine.cpp'; fi`
	$(am__mv) $(DEPDIR)/StatisticEngine.Tpo $(DEPDIR)/StatisticEngine.Po
#	source='src/StatisticEngine.cpp' object='StatisticEngine.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o StatisticEngine.obj `if test -f 'src/StatisticEngine.cpp'; then $(CYGPATH_W) 'src/StatisticEngine.cpp'; else $(CYGPATH_W) '$(srcdir)/src/StatisticEngine.cpp'; fi`

Stream.o: src/Stream.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT Stream.o -MD -MP -MF $(DEPDIR)/Stream.Tpo -c -o Stream.o `test -f 'src/Stream.cpp' || echo '$(srcdir)/'`src/Stream.cpp
	$(am__mv) $(DEPDIR)/Stream.Tpo $(DEPDIR)/Stream.Po
#	source='src/Stream.cpp' object='Stream.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o Stream.o `test -f 'src/Stream.cpp' || echo '$(srcdir)/'`src/Stream.cpp

Stream.obj: src/Stream.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT Stream.obj -MD -MP -MF $(DEPDIR)/Stream.Tpo -c -o Stream.obj `if test -f 'src/Stream.cpp'; then $(CYGPATH_W) 'src/Stream.cpp'; else $(CYGPATH_W) '$(srcdir)/src/Stream.cpp'; fi`
	$(am__mv) $(DEPDIR)/Stream.Tpo $(DEPDIR)/Stream.Po
#	source='src/Stream.cpp' object='Stream.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o Stream.obj `if test -f 'src/Stream.cpp'; then $(CYGPATH_W) 'src/Stream.cpp'; else $(CYGPATH_W) '$(srcdir)/src/Stream.cpp'; fi`

BufferedFile.o: src/BufferedFile.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT BufferedFile.o -MD -MP -MF $(DEPDIR)/BufferedFile.Tpo -c -o BufferedFile.o `test -f 'src/BufferedFile.cpp' || echo '$(srcdir)/'`src/BufferedFile.cpp
	$(am__mv) $(DEPDIR)/BufferedFile.Tpo $(DEPDIR)/BufferedFile.Po
#	source='src/BufferedFile.cpp' object='BufferedFile.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o BufferedFile.o `test -f 'src/BufferedFile.cpp' || echo '$(srcdir)/'`src/BufferedFile.cpp

BufferedFile.obj: src/BufferedFile.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT BufferedFile.obj -MD -MP -MF $(DEPDIR)/BufferedFile.Tpo -c -o BufferedFile.obj `if test -f 'src/BufferedFile.cpp'; then $(CYGPATH_W) 'src/BufferedFile.cpp'; else $(CYGPATH_W) '$(srcdir)/src/BufferedFile.cpp'; fi`
	$(am__mv) $(DEPDIR)/BufferedFile.Tpo $(DEPDIR)/BufferedFile.Po
#	source='src/BufferedFile.cpp' object='BufferedFile.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o BufferedFile.obj `if test -f 'src/BufferedFile.cpp'; then $(CYGPATH_W) 'src/BufferedFile.cpp'; else $(CYGPATH_W) '$(srcdir)/src/BufferedFile.cpp'; fi`

Transformer.o: src/Transformer.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT Transformer.o -MD -MP -MF $(DEPDIR)/Transformer.Tpo -c -o Transformer.o `test -f 'src/Transformer.cpp' || echo '$(srcdir)/'`src/Transformer.cpp
	$(am__mv) $(DEPDIR)/Transformer.Tpo $(DEPDIR)/Transformer.Po
#	source='src/Transformer.cpp' object='Transformer.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o Transformer.o `test -f 'src/Transformer.cpp' || echo '$(srcdir)/'`src/Transformer.cpp

Transformer.obj: src/Transformer.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT Transformer.obj -MD -MP -MF $(DEPDIR)/Transformer.Tpo -c -o Transformer.obj `if test -f 'src/Transformer.cpp'; then $(CYGPATH_W) 'src/Transformer.cpp'; else $(CYGPATH_W) '$(srcdir)/src/Transformer.cpp'; fi`
	$(am__mv) $(DEPDIR)/Transformer.Tpo $(DEPDIR)/Transformer.Po
#	source='src/Transformer.cpp' object='Transformer.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o Transformer.obj `if test -f 'src/Transformer.cpp'; then $(CYGPATH_W) 'src/Transformer.cpp'; else $(CYGPATH_W) '$(srcdir)/src/Transformer.cpp'; fi`

Timer.o: src/Timer.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT Timer.o -MD -MP -MF $(DEPDIR)/Timer.Tpo -c -o Timer.o `test -f 'src/Timer.cpp' || echo '$(srcdir)/'`src/Timer.cpp
	$(am__mv) $(DEPDIR)/Timer.Tpo $(DEPDIR)/Timer.Po
#	source='src/Timer.cpp' object='Timer.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o Timer.o `test -f 'src/Timer.cpp' || echo '$(srcdir)/'`src/Timer.cpp

Timer.obj: src/Timer.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT Timer.obj -MD -MP -MF $(DEPDIR)/Timer.Tpo -c -o Timer.obj `if test -f 'src/Timer.cpp'; then $(CYGPATH_W) 'src/Timer.cpp'; else $(CYGPATH_W) '$(srcdir)/src/Timer.cpp'; fi`
	$(am__mv) $(DEPDIR)/Timer.Tpo $(DEPDIR)/Timer.Po
#	source='src/Timer.cpp' object='Timer.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o Timer.obj `if test -f 'src/Timer.cpp'; then $(CYGPATH_W) 'src/Timer.cpp'; else $(CYGPATH_W) '$(srcdir)/src/Timer.cpp'; fi`

Utils.o: src/Utils.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT Utils.o -MD -MP -MF $(DEPDIR)/Utils.Tpo -c -o Utils.o `test -f 'src/Utils.cpp' || echo '$(srcdir)/'`src/Utils.cpp
	$(am__mv) $(DEPDIR)/Utils.Tpo $(DEPDIR)/Utils.Po
#	source='src/Utils.cpp' object='Utils.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o Utils.o `test -f 'src/Utils.cpp' || echo '$(srcdir)/'`src/Utils.cpp

Utils.obj: src/Utils.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT Utils.obj -MD -MP -MF $(DEPDIR)/Utils.Tpo -c -o Utils.obj `if test -f 'src/Utils.cpp'; then $(CYGPATH_W) 'src/Utils.cpp'; else $(CYGPATH_W) '$(srcdir)/src/Utils.cpp'; fi`
	$(am__mv) $(DEPDIR)/Utils.Tpo $(DEPDIR)/Utils.Po
#	source='src/Utils.cpp' object='Utils.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o Utils.obj `if test -f 'src/Utils.cpp'; then $(CYGPATH_W) 'src/Utils.cpp'; else $(CYGPATH_W) '$(srcdir)/src/Utils.cpp'; fi`

ArpPacket.o: src/packets/ArpPacket.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT ArpPacket.o -MD -MP -MF $(DEPDIR)/ArpPacket.Tpo -c -o ArpPacket.o `test -f 'src/packets/ArpPacket.cpp' || echo '$(srcdir)/'`src/packets/ArpPacket.cpp
	$(am__mv) $(DEPDIR)/ArpPacket.Tpo $(DEPDIR)/ArpPacket.Po
#	source='src/packets/ArpPacket.cpp' object='ArpPacket.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o ArpPacket.o `test -f 'src/packets/ArpPacket.cpp' || echo '$(srcdir)/'`src/packets/ArpPacket.cpp

ArpPacket.obj: src/packets/ArpPacket.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT ArpPacket.obj -MD -MP -MF $(DEPDIR)/ArpPacket.Tpo -c -o ArpPacket.obj `if test -f 'src/packets/ArpPacket.cpp'; then $(CYGPATH_W) 'src/packets/ArpPacket.cpp'; else $(CYGPATH_W) '$(srcdir)/src/packets/ArpPacket.cpp'; fi`
	$(am__mv) $(DEPDIR)/ArpPacket.Tpo $(DEPDIR)/ArpPacket.Po
#	source='src/packets/ArpPacket.cpp' object='ArpPacket.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o ArpPacket.obj `if test -f 'src/packets/ArpPacket.cpp'; then $(CYGPATH_W) 'src/packets/ArpPacket.cpp'; else $(CYGPATH_W) '$(srcdir)/src/packets/ArpPacket.cpp'; fi`

EthernetPacket.o: src/packets/EthernetPacket.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT EthernetPacket.o -MD -MP -MF $(DEPDIR)/EthernetPacket.Tpo -c -o EthernetPacket.o `test -f 'src/packets/EthernetPacket.cpp' || echo '$(srcdir)/'`src/packets/EthernetPacket.cpp
	$(am__mv) $(DEPDIR)/EthernetPacket.Tpo $(DEPDIR)/EthernetPacket.Po
#	source='src/packets/EthernetPacket.cpp' object='EthernetPacket.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o EthernetPacket.o `test -f 'src/packets/EthernetPacket.cpp' || echo '$(srcdir)/'`src/packets/EthernetPacket.cpp

EthernetPacket.obj: src/packets/EthernetPacket.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT EthernetPacket.obj -MD -MP -MF $(DEPDIR)/EthernetPacket.Tpo -c -o EthernetPacket.obj `if test -f 'src/packets/EthernetPacket.cpp'; then $(CYGPATH_W) 'src/packets/EthernetPacket.cpp'; else $(CYGPATH_W) '$(srcdir)/src/packets/EthernetPacket.cpp'; fi`
	$(am__mv) $(DEPDIR)/EthernetPacket.Tpo $(DEPDIR)/EthernetPacket.Po
#	source='src/packets/EthernetPacket.cpp' object='EthernetPacket.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o EthernetPacket.obj `if test -f 'src/packets/EthernetPacket.cpp'; then $(CYGPATH_W) 'src/packets/EthernetPacket.cpp'; else $(CYGPATH_W) '$(srcdir)/src/packets/EthernetPacket.cpp'; fi`

Frame.o: src/packets/Frame.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT Frame.o -MD -MP -MF $(DEPDIR)/Frame.Tpo -c -o Frame.o `test -f 'src/packets/Frame.cpp' || echo '$(srcdir)/'`src/packets/Frame.cpp
	$(am__mv) $(DEPDIR)/Frame.Tpo $(DEPDIR)/Frame.Po
#	source='src/packets/Frame.cpp' object='Frame.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o Frame.o `test -f 'src/packets/Frame.cpp' || echo '$(srcdir)/'`src/packets/Frame.cpp

Frame.obj: src/packets/Frame.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT Frame.obj -MD -MP -MF $(DEPDIR)/Frame.Tpo -c -o Frame.obj `if test -f 'src/packets/Frame.cpp'; then $(CYGPATH_W) 'src/packets/Frame.cpp'; else $(CYGPATH_W) '$(srcdir)/src/packets/Frame.cpp'; fi`
	$(am__mv) $(DEPDIR)/Frame.Tpo $(DEPDIR)/Frame.Po
#	source='src/packets/Frame.cpp' object='Frame.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o Frame.obj `if test -f 'src/packets/Frame.cpp'; then $(CYGPATH_W) 'src/packets/Frame.cpp'; else $(CYGPATH_W) '$(srcdir)/src/packets/Frame.cpp'; fi`

IcmpPacket.o: src/packets/IcmpPacket.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT IcmpPacket.o -MD -MP -MF $(DEPDIR)/IcmpPacket.Tpo -c -o IcmpPacket.o `test -f 'src/packets/IcmpPacket.cpp' || echo '$(srcdir)/'`src/packets/IcmpPacket.cpp
	$(am__mv) $(DEPDIR)/IcmpPacket.Tpo $(DEPDIR)/IcmpPacket.Po
#	source='src/packets/IcmpPacket.cpp' object='IcmpPacket.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o IcmpPacket.o `test -f 'src/packets/IcmpPacket.cpp' || echo '$(srcdir)/'`src/packets/IcmpPacket.cpp

IcmpPacket.obj: src/packets/IcmpPacket.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT IcmpPacket.obj -MD -MP -MF $(DEPDIR)/IcmpPacket.Tpo -c -o IcmpPacket.obj `if test -f 'src/packets/IcmpPacket.cpp'; then $(CYGPATH_W) 'src/packets/IcmpPacket.cpp'; else $(CYGPATH_W) '$(srcdir)/src/packets/IcmpPacket.cpp'; fi`
	$(am__mv) $(DEPDIR)/IcmpPacket.Tpo $(DEPDIR)/IcmpPacket.Po
#	source='src/packets/IcmpPacket.cpp' object='IcmpPacket.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o IcmpPacket.obj `if test -f 'src/packets/IcmpPacket.cpp'; then $(CYGPATH_W) 'src/packets/IcmpPacket.cpp'; else $(CYGPATH_W) '$(srcdir)/src/packets/IcmpPacket.cpp'; fi`

IpPacket.o: src/packets/IpPacket.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT IpPacket.o -MD -MP -MF $(DEPDIR)/IpPacket.Tpo -c -o IpPacket.o `test -f 'src/packets/IpPacket.cpp' || echo '$(srcdir)/'`src/packets/IpPacket.cpp
	$(am__mv) $(DEPDIR)/IpPacket.Tpo $(DEPDIR)/IpPacket.Po
#	source='src/packets/IpPacket.cpp' object='IpPacket.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o IpPacket.o `test -f 'src/packets/IpPacket.cpp' || echo '$(srcdir)/'`src/packets/IpPacket.cpp

IpPacket.obj: src/packets/IpPacket.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT IpPacket.obj -MD -MP -MF $(DEPDIR)/IpPacket.Tpo -c -o IpPacket.obj `if test -f 'src/packets/IpPacket.cpp'; then $(CYGPATH_W) 'src/packets/IpPacket.cpp'; else $(CYGPATH_W) '$(srcdir)/src/packets/IpPacket.cpp'; fi`
	$(am__mv) $(DEPDIR)/IpPacket.Tpo $(DEPDIR)/IpPacket.Po
#	source='src/packets/IpPacket.cpp' object='IpPacket.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o IpPacket.obj `if test -f 'src/packets/IpPacket.cpp'; then $(CYGPATH_W) 'src/packets/IpPacket.cpp'; else $(CYGPATH_W) '$(srcdir)/src/packets/IpPacket.cpp'; fi`

Ipv6Packet.o: src/packets/Ipv6Packet.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT Ipv6Packet.o -MD -MP -MF $(DEPDIR)/Ipv6Packet.Tpo -c -o Ipv6Packet.o `test -f 'src/packets/Ipv6Packet.cpp' || echo '$(srcdir)/'`src/packets/Ipv6Packet.cpp
	$(am__mv) $(DEPDIR)/Ipv6Packet.Tpo $(DEPDIR)/Ipv6Packet.Po
#	source='src/packets/Ipv6Packet.cpp' object='Ipv6Packet.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o Ipv6Packet.o `test -f 'src/packets/Ipv6Packet.cpp' || echo '$(srcdir)/'`src/packets/Ipv6Packet.cpp

Ipv6Packet.obj: src/packets/Ipv6Packet.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT Ipv6Packet.obj -MD -MP -MF $(DEPDIR)/Ipv6Packet.Tpo -c -o Ipv6Packet.obj `if test -f 'src/packets/Ipv6Packet.cpp'; then $(CYGPATH_W) 'src/packets/Ipv6Packet.cpp'; else $(CYGPATH_W) '$(srcdir)/src/packets/Ipv6Packet.cpp'; fi`
	$(am__mv) $(DEPDIR)/Ipv6Packet.Tpo $(DEPDIR)/Ipv6Packet.Po
#	source='src/packets/Ipv6Packet.cpp' object='Ipv6Packet.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o Ipv6Packet.obj `if test -f 'src/packets/Ipv6Packet.cpp'; then $(CYGPATH_W) 'src/packets/Ipv6Packet.cpp'; else $(CYGPATH_W) '$(srcdir)/src/packets/Ipv6Packet.cpp'; fi`

Packet.o: src/packets/Packet.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT Packet.o -MD -MP -MF $(DEPDIR)/Packet.Tpo -c -o Packet.o `test -f 'src/packets/Packet.cpp' || echo '$(srcdir)/'`src/packets/Packet.cpp
	$(am__mv) $(DEPDIR)/Packet.Tpo $(DEPDIR)/Packet.Po
#	source='src/packets/Packet.cpp' object='Packet.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o Packet.o `test -f 'src/packets/Packet.cpp' || echo '$(srcdir)/'`src/packets/Packet.cpp

Packet.obj: src/packets/Packet.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT Packet.obj -MD -MP -MF $(DEPDIR)/Packet.Tpo -c -o Packet.obj `if test -f 'src/packets/Packet.cpp'; then $(CYGPATH_W) 'src/packets/Packet.cpp'; else $(CYGPATH_W) '$(srcdir)/src/packets/Packet.cpp'; fi`
	$(am__mv) $(DEPDIR)/Packet.Tpo $(DEPDIR)/Packet.Po
#	source='src/packets/Packet.cpp' object='Packet.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o Packet.obj `if test -f 'src/packets/Packet.cpp'; then $(CYGPATH_W) 'src/packets/Packet.cpp'; else $(CYGPATH_W) '$(srcdir)/src/packets/Packet.cpp'; fi`

PayloadPacket.o: src/packets/PayloadPacket.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT PayloadPacket.o -MD -MP -MF $(DEPDIR)/PayloadPacket.Tpo -c -o PayloadPacket.o `test -f 'src/packets/PayloadPacket.cpp' || echo '$(srcdir)/'`src/packets/PayloadPacket.cpp
	$(am__mv) $(DEPDIR)/PayloadPacket.Tpo $(DEPDIR)/PayloadPacket.Po
#	source='src/packets/PayloadPacket.cpp' object='PayloadPacket.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o PayloadPacket.o `test -f 'src/packets/PayloadPacket.cpp' || echo '$(srcdir)/'`src/packets/PayloadPacket.cpp

PayloadPacket.obj: src/packets/PayloadPacket.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT PayloadPacket.obj -MD -MP -MF $(DEPDIR)/PayloadPacket.Tpo -c -o PayloadPacket.obj `if test -f 'src/packets/PayloadPacket.cpp'; then $(CYGPATH_W) 'src/packets/PayloadPacket.cpp'; else $(CYGPATH_W) '$(srcdir)/src/packets/PayloadPacket.cpp'; fi`
	$(am__mv) $(DEPDIR)/PayloadPacket.Tpo $(DEPDIR)/PayloadPacket.Po
#	source='src/packets/PayloadPacket.cpp' object='PayloadPacket.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o PayloadPacket.obj `if test -f 'src/packets/PayloadPacket.cpp'; then $(CYGPATH_W) 'src/packets/PayloadPacket.cpp'; else $(CYGPATH_W) '$(srcdir)/src/packets/PayloadPacket.cpp'; fi`

TcpPacket.o: src/packets/TcpPacket.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT TcpPacket.o -MD -MP -MF $(DEPDIR)/TcpPacket.Tpo -c -o TcpPacket.o `test -f 'src/packets/TcpPacket.cpp' || echo '$(srcdir)/'`src/packets/TcpPacket.cpp
	$(am__mv) $(DEPDIR)/TcpPacket.Tpo $(DEPDIR)/TcpPacket.Po
#	source='src/packets/TcpPacket.cpp' object='TcpPacket.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o TcpPacket.o `test -f 'src/packets/TcpPacket.cpp' || echo '$(srcdir)/'`src/packets/TcpPacket.cpp

TcpPacket.obj: src/packets/TcpPacket.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT TcpPacket.obj -MD -MP -MF $(DEPDIR)/TcpPacket.Tpo -c -o TcpPacket.obj `if test -f 'src/packets/TcpPacket.cpp'; then $(CYGPATH_W) 'src/packets/TcpPacket.cpp'; else $(CYGPATH_W) '$(srcdir)/src/packets/TcpPacket.cpp'; fi`
	$(am__mv) $(DEPDIR)/TcpPacket.Tpo $(DEPDIR)/TcpPacket.Po
#	source='src/packets/TcpPacket.cpp' object='TcpPacket.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o TcpPacket.obj `if test -f 'src/packets/TcpPacket.cpp'; then $(CYGPATH_W) 'src/packets/TcpPacket.cpp'; else $(CYGPATH_W) '$(srcdir)/src/packets/TcpPacket.cpp'; fi`

UdpPacket.o: src/packets/UdpPacket.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT UdpPacket.o -MD -MP -MF $(DEPDIR)/UdpPacket.Tpo -c -o UdpPacket.o `test -f 'src/packets/UdpPacket.cpp' || echo '$(srcdir)/'`src/packets/UdpPacket.cpp
	$(am__mv) $(DEPDIR)/UdpPacket.Tpo $(DEPDIR)/UdpPacket.Po
#	source='src/packets/UdpPacket.cpp' object='UdpPacket.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o UdpPacket.o `test -f 'src/packets/UdpPacket.cpp' || echo '$(srcdir)/'`src/packets/UdpPacket.cpp

UdpPacket.obj: src/packets/UdpPacket.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT UdpPacket.obj -MD -MP -MF $(DEPDIR)/UdpPacket.Tpo -c -o UdpPacket.obj `if test -f 'src/packets/UdpPacket.cpp'; then $(CYGPATH_W) 'src/packets/UdpPacket.cpp'; else $(CYGPATH_W) '$(srcdir)/src/packets/UdpPacket.cpp'; fi`
	$(am__mv) $(DEPDIR)/UdpPacket.Tpo $(DEPDIR)/UdpPacket.Po
#	source='src/packets/UdpPacket.cpp' object='UdpPacket.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o UdpPacket.obj `if test -f 'src/packets/UdpPacket.cpp'; then $(CYGPATH_W) 'src/packets/UdpPacket.cpp'; else $(CYGPATH_W) '$(srcdir)/src/packets/UdpPacket.cpp'; fi`

PacketFactory.o: src/packets/PacketFactory.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT PacketFactory.o -MD -MP -MF $(DEPDIR)/PacketFactory.Tpo -c -o PacketFactory.o `test -f 'src/packets/PacketFactory.cpp' || echo '$(srcdir)/'`src/packets/PacketFactory.cpp
	$(am__mv) $(DEPDIR)/PacketFactory.Tpo $(DEPDIR)/PacketFactory.Po
#	source='src/packets/PacketFactory.cpp' object='PacketFactory.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o PacketFactory.o `test -f 'src/packets/PacketFactory.cpp' || echo '$(srcdir)/'`src/packets/PacketFactory.cpp

PacketFactory.obj: src/packets/PacketFactory.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT PacketFactory.obj -MD -MP -MF $(DEPDIR)/PacketFactory.Tpo -c -o PacketFactory.obj `if test -f 'src/packets/PacketFactory.cpp'; then $(CYGPATH_W) 'src/packets/PacketFactory.cpp'; else $(CYGPATH_W) '$(srcdir)/src/packets/PacketFactory.cpp'; fi`
	$(am__mv) $(DEPDIR)/PacketFactory.Tpo $(DEPDIR)/PacketFactory.Po
#	source='src/packets/PacketFactory.cpp' object='PacketFactory.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o PacketFactory.obj `if test -f 'src/packets/PacketFactory.cpp'; then $(CYGPATH_W) 'src/packets/PacketFactory.cpp'; else $(CYGPATH_W) '$(srcdir)/src/packets/PacketFactory.cpp'; fi`

VlanPacket.o: src/packets/VlanPacket.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT VlanPacket.o -MD -MP -MF $(DEPDIR)/VlanPacket.Tpo -c -o VlanPacket.o `test -f 'src/packets/VlanPacket.cpp' || echo '$(srcdir)/'`src/packets/VlanPacket.cpp
	$(am__mv) $(DEPDIR)/VlanPacket.Tpo $(DEPDIR)/VlanPacket.Po
#	source='src/packets/VlanPacket.cpp' object='VlanPacket.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o VlanPacket.o `test -f 'src/packets/VlanPacket.cpp' || echo '$(srcdir)/'`src/packets/VlanPacket.cpp

VlanPacket.obj: src/packets/VlanPacket.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT VlanPacket.obj -MD -MP -MF $(DEPDIR)/VlanPacket.Tpo -c -o VlanPacket.obj `if test -f 'src/packets/VlanPacket.cpp'; then $(CYGPATH_W) 'src/packets/VlanPacket.cpp'; else $(CYGPATH_W) '$(srcdir)/src/packets/VlanPacket.cpp'; fi`
	$(am__mv) $(DEPDIR)/VlanPacket.Tpo $(DEPDIR)/VlanPacket.Po
#	source='src/packets/VlanPacket.cpp' object='VlanPacket.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o VlanPacket.obj `if test -f 'src/packets/VlanPacket.cpp'; then $(CYGPATH_W) 'src/packets/VlanPacket.cpp'; else $(CYGPATH_W) '$(srcdir)/src/packets/VlanPacket.cpp'; fi`

sha1.o: src/anonprimitives/hmacsha1/sha1.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT sha1.o -MD -MP -MF $(DEPDIR)/sha1.Tpo -c -o sha1.o `test -f 'src/anonprimitives/hmacsha1/sha1.cpp' || echo '$(srcdir)/'`src/anonprimitives/hmacsha1/sha1.cpp
	$(am__mv) $(DEPDIR)/sha1.Tpo $(DEPDIR)/sha1.Po
#	source='src/anonprimitives/hmacsha1/sha1.cpp' object='sha1.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o sha1.o `test -f 'src/anonprimitives/hmacsha1/sha1.cpp' || echo '$(srcdir)/'`src/anonprimitives/hmacsha1/sha1.cpp

sha1.obj: src/anonprimitives/hmacsha1/sha1.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT sha1.obj -MD -MP -MF $(DEPDIR)/sha1.Tpo -c -o sha1.obj `if test -f 'src/anonprimitives/hmacsha1/sha1.cpp'; then $(CYGPATH_W) 'src/anonprimitives/hmacsha1/sha1.cpp'; else $(CYGPATH_W) '$(srcdir)/src/anonprimitives/hmacsha1/sha1.cpp'; fi`
	$(am__mv) $(DEPDIR)/sha1.Tpo $(DEPDIR)/sha1.Po
#	source='src/anonprimitives/hmacsha1/sha1.cpp' object='sha1.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o sha1.obj `if test -f 'src/anonprimitives/hmacsha1/sha1.cpp'; then $(CYGPATH_W) 'src/anonprimitives/hmacsha1/sha1.cpp'; else $(CYGPATH_W) '$(srcdir)/src/anonprimitives/hmacsha1/sha1.cpp'; fi`

sha1_hmac.o: src/anonprimitives/hmacsha1/sha1_hmac.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT sha1_hmac.o -MD -MP -MF $(DEPDIR)/sha1_hmac.Tpo -c -o sha1_hmac.o `test -f 'src/anonprimitives/hmacsha1/sha1_hmac.cpp' || echo '$(srcdir)/'`src/anonprimitives/hmacsha1/sha1_hmac.cpp
	$(am__mv) $(DEPDIR)/sha1_hmac.Tpo $(DEPDIR)/sha1_hmac.Po
#	source='src/anonprimitives/hmacsha1/sha1_hmac.cpp' object='sha1_hmac.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o sha1_hmac.o `test -f 'src/anonprimitives/hmacsha1/sha1_hmac.cpp' || echo '$(srcdir)/'`src/anonprimitives/hmacsha1/sha1_hmac.cpp

sha1_hmac.obj: src/anonprimitives/hmacsha1/sha1_hmac.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT sha1_hmac.obj -MD -MP -MF $(DEPDIR)/sha1_hmac.Tpo -c -o sha1_hmac.obj `if test -f 'src/anonprimitives/hmacsha1/sha1_hmac.cpp'; then $(CYGPATH_W) 'src/anonprimitives/hmacsha1/sha1_hmac.cpp'; else $(CYGPATH_W) '$(srcdir)/src/anonprimitives/hmacsha1/sha1_hmac.cpp'; fi`
	$(am__mv) $(DEPDIR)/sha1_hmac.Tpo $(DEPDIR)/sha1_hmac.Po
#	source='src/anonprimitives/hmacsha1/sha1_hmac.cpp' object='sha1_hmac.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o sha1_hmac.obj `if test -f 'src/anonprimitives/hmacsha1/sha1_hmac.cpp'; then $(CYGPATH_W) 'src/anonprimitives/hmacsha1/sha1_hmac.cpp'; else $(CYGPATH_W) '$(srcdir)/src/anonprimitives/hmacsha1/sha1_hmac.cpp'; fi`

rijndael.o: src/anonprimitives/cryptopan/rijndael.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT rijndael.o -MD -MP -MF $(DEPDIR)/rijndael.Tpo -c -o rijndael.o `test -f 'src/anonprimitives/cryptopan/rijndael.cpp' || echo '$(srcdir)/'`src/anonprimitives/cryptopan/rijndael.cpp
	$(am__mv) $(DEPDIR)/rijndael.Tpo $(DEPDIR)/rijndael.Po
#	source='src/anonprimitives/cryptopan/rijndael.cpp' object='rijndael.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o rijndael.o `test -f 'src/anonprimitives/cryptopan/rijndael.cpp' || echo '$(srcdir)/'`src/anonprimitives/cryptopan/rijndael.cpp

rijndael.obj: src/anonprimitives/cryptopan/rijndael.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT rijndael.obj -MD -MP -MF $(DEPDIR)/rijndael.Tpo -c -o rijndael.obj `if test -f 'src/anonprimitives/cryptopan/rijndael.cpp'; then $(CYGPATH_W) 'src/anonprimitives/cryptopan/rijndael.cpp'; else $(CYGPATH_W) '$(srcdir)/src/anonprimitives/cryptopan/rijndael.cpp'; fi`
	$(am__mv) $(DEPDIR)/rijndael.Tpo $(DEPDIR)/rijndael.Po
#	source='src/anonprimitives/cryptopan/rijndael.cpp' object='rijndael.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o rijndael.obj `if test -f 'src/anonprimitives/cryptopan/rijndael.cpp'; then $(CYGPATH_W) 'src/anonprimitives/cryptopan/rijndael.cpp'; else $(CYGPATH_W) '$(srcdir)/src/anonprimitives/cryptopan/rijndael.cpp'; fi`

panonymizer.o: src/anonprimitives/cryptopan/panonymizer.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT panonymizer.o -MD -MP -MF $(DEPDIR)/panonymizer.Tpo -c -o panonymizer.o `test -f 'src/anonprimitives/cryptopan/panonymizer.cpp' || echo '$(srcdir)/'`src/anonprimitives/cryptopan/panonymizer.cpp
	$(am__mv) $(DEPDIR)/panonymizer.Tpo $(DEPDIR)/panonymizer.Po
#	source='src/anonprimitives/cryptopan/panonymizer.cpp' object='panonymizer.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o panonymizer.o `test -f 'src/anonprimitives/cryptopan/panonymizer.cpp' || echo '$(srcdir)/'`src/anonprimitives/cryptopan/panonymizer.cpp

panonymizer.obj: src/anonprimitives/cryptopan/panonymizer.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT panonymizer.obj -MD -MP -MF $(DEPDIR)/panonymizer.Tpo -c -o panonymizer.obj `if test -f 'src/anonprimitives/cryptopan/panonymizer.cpp'; then $(CYGPATH_W) 'src/anonprimitives/cryptopan/panonymizer.cpp'; else $(CYGPATH_W) '$(srcdir)/src/anonprimitives/cryptopan/panonymizer.cpp'; fi`
	$(am__mv) $(DEPDIR)/panonymizer.Tpo $(DEPDIR)/panonymizer.Po
#	source='src/anonprimitives/cryptopan/panonymizer.cpp' object='panonymizer.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o panonymizer.obj `if test -f 'src/anonprimitives/cryptopan/panonymizer.cpp'; then $(CYGPATH_W) 'src/anonprimitives/cryptopan/panonymizer.cpp'; else $(CYGPATH_W) '$(srcdir)/src/anonprimitives/cryptopan/panonymizer.cpp'; fi`

AnonBroadcastHandler.o: src/anonprimitives/AnonBroadcastHandler.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT AnonBroadcastHandler.o -MD -MP -MF $(DEPDIR)/AnonBroadcastHandler.Tpo -c -o AnonBroadcastHandler.o `test -f 'src/anonprimitives/AnonBroadcastHandler.cpp' || echo '$(srcdir)/'`src/anonprimitives/AnonBroadcastHandler.cpp
	$(am__mv) $(DEPDIR)/AnonBroadcastHandler.Tpo $(DEPDIR)/AnonBroadcastHandler.Po
#	source='src/anonprimitives/AnonBroadcastHandler.cpp' object='AnonBroadcastHandler.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o AnonBroadcastHandler.o `test -f 'src/anonprimitives/AnonBroadcastHandler.cpp' || echo '$(srcdir)/'`src/anonprimitives/AnonBroadcastHandler.cpp

AnonBroadcastHandler.obj: src/anonprimitives/AnonBroadcastHandler.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT AnonBroadcastHandler.obj -MD -MP -MF $(DEPDIR)/AnonBroadcastHandler.Tpo -c -o AnonBroadcastHandler.obj `if test -f 'src/anonprimitives/AnonBroadcastHandler.cpp'; then $(CYGPATH_W) 'src/anonprimitives/AnonBroadcastHandler.cpp'; else $(CYGPATH_W) '$(srcdir)/src/anonprimitives/AnonBroadcastHandler.cpp'; fi`
	$(am__mv) $(DEPDIR)/AnonBroadcastHandler.Tpo $(DEPDIR)/AnonBroadcastHandler.Po
#	source='src/anonprimitives/AnonBroadcastHandler.cpp' object='AnonBroadcastHandler.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o AnonBroadcastHandler.obj `if test -f 'src/anonprimitives/AnonBroadcastHandler.cpp'; then $(CYGPATH_W) 'src/anonprimitives/AnonBroadcastHandler.cpp'; else $(CYGPATH_W) '$(srcdir)/src/anonprimitives/AnonBroadcastHandler.cpp'; fi`

AnonBytewise.o: src/anonprimitives/AnonBytewise.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT AnonBytewise.o -MD -MP -MF $(DEPDIR)/AnonBytewise.Tpo -c -o AnonBytewise.o `test -f 'src/anonprimitives/AnonBytewise.cpp' || echo '$(srcdir)/'`src/anonprimitives/AnonBytewise.cpp
	$(am__mv) $(DEPDIR)/AnonBytewise.Tpo $(DEPDIR)/AnonBytewise.Po
#	source='src/anonprimitives/AnonBytewise.cpp' object='AnonBytewise.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o AnonBytewise.o `test -f 'src/anonprimitives/AnonBytewise.cpp' || echo '$(srcdir)/'`src/anonprimitives/AnonBytewise.cpp

AnonBytewise.obj: src/anonprimitives/AnonBytewise.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT AnonBytewise.obj -MD -MP -MF $(DEPDIR)/AnonBytewise.Tpo -c -o AnonBytewise.obj `if test -f 'src/anonprimitives/AnonBytewise.cpp'; then $(CYGPATH_W) 'src/anonprimitives/AnonBytewise.cpp'; else $(CYGPATH_W) '$(srcdir)/src/anonprimitives/AnonBytewise.cpp'; fi`
	$(am__mv) $(DEPDIR)/AnonBytewise.Tpo $(DEPDIR)/AnonBytewise.Po
#	source='src/anonprimitives/AnonBytewise.cpp' object='AnonBytewise.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o AnonBytewise.obj `if test -f 'src/anonprimitives/AnonBytewise.cpp'; then $(CYGPATH_W) 'src/anonprimitives/AnonBytewise.cpp'; else $(CYGPATH_W) '$(srcdir)/src/anonprimitives/AnonBytewise.cpp'; fi`

AnonBytewiseHashHmacSha1.o: src/anonprimitives/AnonBytewiseHashHmacSha1.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT AnonBytewiseHashHmacSha1.o -MD -MP -MF $(DEPDIR)/AnonBytewiseHashHmacSha1.Tpo -c -o AnonBytewiseHashHmacSha1.o `test -f 'src/anonprimitives/AnonBytewiseHashHmacSha1.cpp' || echo '$(srcdir)/'`src/anonprimitives/AnonBytewiseHashHmacSha1.cpp
	$(am__mv) $(DEPDIR)/AnonBytewiseHashHmacSha1.Tpo $(DEPDIR)/AnonBytewiseHashHmacSha1.Po
#	source='src/anonprimitives/AnonBytewiseHashHmacSha1.cpp' object='AnonBytewiseHashHmacSha1.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o AnonBytewiseHashHmacSha1.o `test -f 'src/anonprimitives/AnonBytewiseHashHmacSha1.cpp' || echo '$(srcdir)/'`src/anonprimitives/AnonBytewiseHashHmacSha1.cpp

AnonBytewiseHashHmacSha1.obj: src/anonprimitives/AnonBytewiseHashHmacSha1.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT AnonBytewiseHashHmacSha1.obj -MD -MP -MF $(DEPDIR)/AnonBytewiseHashHmacSha1.Tpo -c -o AnonBytewiseHashHmacSha1.obj `if test -f 'src/anonprimitives/AnonBytewiseHashHmacSha1.cpp'; then $(CYGPATH_W) 'src/anonprimitives/AnonBytewiseHashHmacSha1.cpp'; else $(CYGPATH_W) '$(srcdir)/src/anonprimitives/AnonBytewiseHashHmacSha1.cpp'; fi`
	$(am__mv) $(DEPDIR)/AnonBytewiseHashHmacSha1.Tpo $(DEPDIR)/AnonBytewiseHashHmacSha1.Po
#	source='src/anonprimitives/AnonBytewiseHashHmacSha1.cpp' object='AnonBytewiseHashHmacSha1.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o AnonBytewiseHashHmacSha1.obj `if test -f 'src/anonprimitives/AnonBytewiseHashHmacSha1.cpp'; then $(CYGPATH_W) 'src/anonprimitives/AnonBytewiseHashHmacSha1.cpp'; else $(CYGPATH_W) '$(srcdir)/src/anonprimitives/AnonBytewiseHashHmacSha1.cpp'; fi`

AnonBytewiseHashSha1.o: src/anonprimitives/AnonBytewiseHashSha1.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT AnonBytewiseHashSha1.o -MD -MP -MF $(DEPDIR)/AnonBytewiseHashSha1.Tpo -c -o AnonBytewiseHashSha1.o `test -f 'src/anonprimitives/AnonBytewiseHashSha1.cpp' || echo '$(srcdir)/'`src/anonprimitives/AnonBytewiseHashSha1.cpp
	$(am__mv) $(DEPDIR)/AnonBytewiseHashSha1.Tpo $(DEPDIR)/AnonBytewiseHashSha1.Po
#	source='src/anonprimitives/AnonBytewiseHashSha1.cpp' object='AnonBytewiseHashSha1.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o AnonBytewiseHashSha1.o `test -f 'src/anonprimitives/AnonBytewiseHashSha1.cpp' || echo '$(srcdir)/'`src/anonprimitives/AnonBytewiseHashSha1.cpp

AnonBytewiseHashSha1.obj: src/anonprimitives/AnonBytewiseHashSha1.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT AnonBytewiseHashSha1.obj -MD -MP -MF $(DEPDIR)/AnonBytewiseHashSha1.Tpo -c -o AnonBytewiseHashSha1.obj `if test -f 'src/anonprimitives/AnonBytewiseHashSha1.cpp'; then $(CYGPATH_W) 'src/anonprimitives/AnonBytewiseHashSha1.cpp'; else $(CYGPATH_W) '$(srcdir)/src/anonprimitives/AnonBytewiseHashSha1.cpp'; fi`
	$(am__mv) $(DEPDIR)/AnonBytewiseHashSha1.Tpo $(DEPDIR)/AnonBytewiseHashSha1.Po
#	source='src/anonprimitives/AnonBytewiseHashSha1.cpp' object='AnonBytewiseHashSha1.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o AnonBytewiseHashSha1.obj `if test -f 'src/anonprimitives/AnonBytewiseHashSha1.cpp'; then $(CYGPATH_W) 'src/anonprimitives/AnonBytewiseHashSha1.cpp'; else $(CYGPATH_W) '$(srcdir)/src/anonprimitives/AnonBytewiseHashSha1.cpp'; fi`

AnonConstOverwrite.o: src/anonprimitives/AnonConstOverwrite.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT AnonConstOverwrite.o -MD -MP -MF $(DEPDIR)/AnonConstOverwrite.Tpo -c -o AnonConstOverwrite.o `test -f 'src/anonprimitives/AnonConstOverwrite.cpp' || echo '$(srcdir)/'`src/anonprimitives/AnonConstOverwrite.cpp
	$(am__mv) $(DEPDIR)/AnonConstOverwrite.Tpo $(DEPDIR)/AnonConstOverwrite.Po
#	source='src/anonprimitives/AnonConstOverwrite.cpp' object='AnonConstOverwrite.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o AnonConstOverwrite.o `test -f 'src/anonprimitives/AnonConstOverwrite.cpp' || echo '$(srcdir)/'`src/anonprimitives/AnonConstOverwrite.cpp

AnonConstOverwrite.obj: src/anonprimitives/AnonConstOverwrite.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT AnonConstOverwrite.obj -MD -MP -MF $(DEPDIR)/AnonConstOverwrite.Tpo -c -o AnonConstOverwrite.obj `if test -f 'src/anonprimitives/AnonConstOverwrite.cpp'; then $(CYGPATH_W) 'src/anonprimitives/AnonConstOverwrite.cpp'; else $(CYGPATH_W) '$(srcdir)/src/anonprimitives/AnonConstOverwrite.cpp'; fi`
	$(am__mv) $(DEPDIR)/AnonConstOverwrite.Tpo $(DEPDIR)/AnonConstOverwrite.Po
#	source='src/anonprimitives/AnonConstOverwrite.cpp' object='AnonConstOverwrite.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o AnonConstOverwrite.obj `if test -f 'src/anonprimitives/AnonConstOverwrite.cpp'; then $(CYGPATH_W) 'src/anonprimitives/AnonConstOverwrite.cpp'; else $(CYGPATH_W) '$(srcdir)/src/anonprimitives/AnonConstOverwrite.cpp'; fi`

AnonContinuousChar.o: src/anonprimitives/AnonContinuousChar.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT AnonContinuousChar.o -MD -MP -MF $(DEPDIR)/AnonContinuousChar.Tpo -c -o AnonContinuousChar.o `test -f 'src/anonprimitives/AnonContinuousChar.cpp' || echo '$(srcdir)/'`src/anonprimitives/AnonContinuousChar.cpp
	$(am__mv) $(DEPDIR)/AnonContinuousChar.Tpo $(DEPDIR)/AnonContinuousChar.Po
#	source='src/anonprimitives/AnonContinuousChar.cpp' object='AnonContinuousChar.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o AnonContinuousChar.o `test -f 'src/anonprimitives/AnonContinuousChar.cpp' || echo '$(srcdir)/'`src/anonprimitives/AnonContinuousChar.cpp

AnonContinuousChar.obj: src/anonprimitives/AnonContinuousChar.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT AnonContinuousChar.obj -MD -MP -MF $(DEPDIR)/AnonContinuousChar.Tpo -c -o AnonContinuousChar.obj `if test -f 'src/anonprimitives/AnonContinuousChar.cpp'; then $(CYGPATH_W) 'src/anonprimitives/AnonContinuousChar.cpp'; else $(CYGPATH_W) '$(srcdir)/src/anonprimitives/AnonContinuousChar.cpp'; fi`
	$(am__mv) $(DEPDIR)/AnonContinuousChar.Tpo $(DEPDIR)/AnonContinuousChar.Po
#	source='src/anonprimitives/AnonContinuousChar.cpp' object='AnonContinuousChar.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o AnonContinuousChar.obj `if test -f 'src/anonprimitives/AnonContinuousChar.cpp'; then $(CYGPATH_W) 'src/anonprimitives/AnonContinuousChar.cpp'; else $(CYGPATH_W) '$(srcdir)/src/anonprimitives/AnonContinuousChar.cpp'; fi`

AnonFactory.o: src/anonprimitives/AnonFactory.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT AnonFactory.o -MD -MP -MF $(DEPDIR)/AnonFactory.Tpo -c -o AnonFactory.o `test -f 'src/anonprimitives/AnonFactory.cpp' || echo '$(srcdir)/'`src/anonprimitives/AnonFactory.cpp
	$(am__mv) $(DEPDIR)/AnonFactory.Tpo $(DEPDIR)/AnonFactory.Po
#	source='src/anonprimitives/AnonFactory.cpp' object='AnonFactory.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o AnonFactory.o `test -f 'src/anonprimitives/AnonFactory.cpp' || echo '$(srcdir)/'`src/anonprimitives/AnonFactory.cpp

AnonFactory.obj: src/anonprimitives/AnonFactory.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT AnonFactory.obj -MD -MP -MF $(DEPDIR)/AnonFactory.Tpo -c -o AnonFactory.obj `if test -f 'src/anonprimitives/AnonFactory.cpp'; then $(CYGPATH_W) 'src/anonprimitives/AnonFactory.cpp'; else $(CYGPATH_W) '$(srcdir)/src/anonprimitives/AnonFactory.cpp'; fi`
	$(am__mv) $(DEPDIR)/AnonFactory.Tpo $(DEPDIR)/AnonFactory.Po
#	source='src/anonprimitives/AnonFactory.cpp' object='AnonFactory.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o AnonFactory.obj `if test -f 'src/anonprimitives/AnonFactory.cpp'; then $(CYGPATH_W) 'src/anonprimitives/AnonFactory.cpp'; else $(CYGPATH_W) '$(srcdir)/src/anonprimitives/AnonFactory.cpp'; fi`

AnonHashHmacSha1.o: src/anonprimitives/AnonHashHmacSha1.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT AnonHashHmacSha1.o -MD -MP -MF $(DEPDIR)/AnonHashHmacSha1.Tpo -c -o AnonHashHmacSha1.o `test -f 'src/anonprimitives/AnonHashHmacSha1.cpp' || echo '$(srcdir)/'`src/anonprimitives/AnonHashHmacSha1.cpp
	$(am__mv) $(DEPDIR)/AnonHashHmacSha1.Tpo $(DEPDIR)/AnonHashHmacSha1.Po
#	source='src/anonprimitives/AnonHashHmacSha1.cpp' object='AnonHashHmacSha1.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o AnonHashHmacSha1.o `test -f 'src/anonprimitives/AnonHashHmacSha1.cpp' || echo '$(srcdir)/'`src/anonprimitives/AnonHashHmacSha1.cpp

AnonHashHmacSha1.obj: src/anonprimitives/AnonHashHmacSha1.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT AnonHashHmacSha1.obj -MD -MP -MF $(DEPDIR)/AnonHashHmacSha1.Tpo -c -o AnonHashHmacSha1.obj `if test -f 'src/anonprimitives/AnonHashHmacSha1.cpp'; then $(CYGPATH_W) 'src/anonprimitives/AnonHashHmacSha1.cpp'; else $(CYGPATH_W) '$(srcdir)/src/anonprimitives/AnonHashHmacSha1.cpp'; fi`
	$(am__mv) $(DEPDIR)/AnonHashHmacSha1.Tpo $(DEPDIR)/AnonHashHmacSha1.Po
#	source='src/anonprimitives/AnonHashHmacSha1.cpp' object='AnonHashHmacSha1.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o AnonHashHmacSha1.obj `if test -f 'src/anonprimitives/AnonHashHmacSha1.cpp'; then $(CYGPATH_W) 'src/anonprimitives/AnonHashHmacSha1.cpp'; else $(CYGPATH_W) '$(srcdir)/src/anonprimitives/AnonHashHmacSha1.cpp'; fi`

AnonHashSha1.o: src/anonprimitives/AnonHashSha1.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT AnonHashSha1.o -MD -MP -MF $(DEPDIR)/AnonHashSha1.Tpo -c -o AnonHashSha1.o `test -f 'src/anonprimitives/AnonHashSha1.cpp' || echo '$(srcdir)/'`src/anonprimitives/AnonHashSha1.cpp
	$(am__mv) $(DEPDIR)/AnonHashSha1.Tpo $(DEPDIR)/AnonHashSha1.Po
#	source='src/anonprimitives/AnonHashSha1.cpp' object='AnonHashSha1.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o AnonHashSha1.o `test -f 'src/anonprimitives/AnonHashSha1.cpp' || echo '$(srcdir)/'`src/anonprimitives/AnonHashSha1.cpp

AnonHashSha1.obj: src/anonprimitives/AnonHashSha1.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT AnonHashSha1.obj -MD -MP -MF $(DEPDIR)/AnonHashSha1.Tpo -c -o AnonHashSha1.obj `if test -f 'src/anonprimitives/AnonHashSha1.cpp'; then $(CYGPATH_W) 'src/anonprimitives/AnonHashSha1.cpp'; else $(CYGPATH_W) '$(srcdir)/src/anonprimitives/AnonHashSha1.cpp'; fi`
	$(am__mv) $(DEPDIR)/AnonHashSha1.Tpo $(DEPDIR)/AnonHashSha1.Po
#	source='src/anonprimitives/AnonHashSha1.cpp' object='AnonHashSha1.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o AnonHashSha1.obj `if test -f 'src/anonprimitives/AnonHashSha1.cpp'; then $(CYGPATH_W) 'src/anonprimitives/AnonHashSha1.cpp'; else $(CYGPATH_W) '$(srcdir)/src/anonprimitives/AnonHashSha1.cpp'; fi`

AnonIdentity.o: src/anonprimitives/AnonIdentity.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT AnonIdentity.o -MD -MP -MF $(DEPDIR)/AnonIdentity.Tpo -c -o AnonIdentity.o `test -f 'src/anonprimitives/AnonIdentity.cpp' || echo '$(srcdir)/'`src/anonprimitives/AnonIdentity.cpp
	$(am__mv) $(DEPDIR)/AnonIdentity.Tpo $(DEPDIR)/AnonIdentity.Po
#	source='src/anonprimitives/AnonIdentity.cpp' object='AnonIdentity.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o AnonIdentity.o `test -f 'src/anonprimitives/AnonIdentity.cpp' || echo '$(srcdir)/'`src/anonprimitives/AnonIdentity.cpp

AnonIdentity.obj: src/anonprimitives/AnonIdentity.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT AnonIdentity.obj -MD -MP -MF $(DEPDIR)/AnonIdentity.Tpo -c -o AnonIdentity.obj `if test -f 'src/anonprimitives/AnonIdentity.cpp'; then $(CYGPATH_W) 'src/anonprimitives/AnonIdentity.cpp'; else $(CYGPATH_W) '$(srcdir)/src/anonprimitives/AnonIdentity.cpp'; fi`
	$(am__mv) $(DEPDIR)/AnonIdentity.Tpo $(DEPDIR)/AnonIdentity.Po
#	source='src/anonprimitives/AnonIdentity.cpp' object='AnonIdentity.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o AnonIdentity.obj `if test -f 'src/anonprimitives/AnonIdentity.cpp'; then $(CYGPATH_W) 'src/anonprimitives/AnonIdentity.cpp'; else $(CYGPATH_W) '$(srcdir)/src/anonprimitives/AnonIdentity.cpp'; fi`

AnonPrimitive.o: src/anonprimitives/AnonPrimitive.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT AnonPrimitive.o -MD -MP -MF $(DEPDIR)/AnonPrimitive.Tpo -c -o AnonPrimitive.o `test -f 'src/anonprimitives/AnonPrimitive.cpp' || echo '$(srcdir)/'`src/anonprimitives/AnonPrimitive.cpp
	$(am__mv) $(DEPDIR)/AnonPrimitive.Tpo $(DEPDIR)/AnonPrimitive.Po
#	source='src/anonprimitives/AnonPrimitive.cpp' object='AnonPrimitive.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o AnonPrimitive.o `test -f 'src/anonprimitives/AnonPrimitive.cpp' || echo '$(srcdir)/'`src/anonprimitives/AnonPrimitive.cpp

AnonPrimitive.obj: src/anonprimitives/AnonPrimitive.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT AnonPrimitive.obj -MD -MP -MF $(DEPDIR)/AnonPrimitive.Tpo -c -o AnonPrimitive.obj `if test -f 'src/anonprimitives/AnonPrimitive.cpp'; then $(CYGPATH_W) 'src/anonprimitives/AnonPrimitive.cpp'; else $(CYGPATH_W) '$(srcdir)/src/anonprimitives/AnonPrimitive.cpp'; fi`
	$(am__mv) $(DEPDIR)/AnonPrimitive.Tpo $(DEPDIR)/AnonPrimitive.Po
#	source='src/anonprimitives/AnonPrimitive.cpp' object='AnonPrimitive.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o AnonPrimitive.obj `if test -f 'src/anonprimitives/AnonPrimitive.cpp'; then $(CYGPATH_W) 'src/anonprimitives/AnonPrimitive.cpp'; else $(CYGPATH_W) '$(srcdir)/src/anonprimitives/AnonPrimitive.cpp'; fi`

AnonRandomize.o: src/anonprimitives/AnonRandomize.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT AnonRandomize.o -MD -MP -MF $(DEPDIR)/AnonRandomize.Tpo -c -o AnonRandomize.o `test -f 'src/anonprimitives/AnonRandomize.cpp' || echo '$(srcdir)/'`src/anonprimitives/AnonRandomize.cpp
	$(am__mv) $(DEPDIR)/AnonRandomize.Tpo $(DEPDIR)/AnonRandomize.Po
#	source='src/anonprimitives/AnonRandomize.cpp' object='AnonRandomize.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o AnonRandomize.o `test -f 'src/anonprimitives/AnonRandomize.cpp' || echo '$(srcdir)/'`src/anonprimitives/AnonRandomize.cpp

AnonRandomize.obj: src/anonprimitives/AnonRandomize.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT AnonRandomize.obj -MD -MP -MF $(DEPDIR)/AnonRandomize.Tpo -c -o AnonRandomize.obj `if test -f 'src/anonprimitives/AnonRandomize.cpp'; then $(CYGPATH_W) 'src/anonprimitives/AnonRandomize.cpp'; else $(CYGPATH_W) '$(srcdir)/src/anonprimitives/AnonRandomize.cpp'; fi`
	$(am__mv) $(DEPDIR)/AnonRandomize.Tpo $(DEPDIR)/AnonRandomize.Po
#	source='src/anonprimitives/AnonRandomize.cpp' object='AnonRandomize.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o AnonRandomize.obj `if test -f 'src/anonprimitives/AnonRandomize.cpp'; then $(CYGPATH_W) 'src/anonprimitives/AnonRandomize.cpp'; else $(CYGPATH_W) '$(srcdir)/src/anonprimitives/AnonRandomize.cpp'; fi`

AnonShorten.o: src/anonprimitives/AnonShorten.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT AnonShorten.o -MD -MP -MF $(DEPDIR)/AnonShorten.Tpo -c -o AnonShorten.o `test -f 'src/anonprimitives/AnonShorten.cpp' || echo '$(srcdir)/'`src/anonprimitives/AnonShorten.cpp
	$(am__mv) $(DEPDIR)/AnonShorten.Tpo $(DEPDIR)/AnonShorten.Po
#	source='src/anonprimitives/AnonShorten.cpp' object='AnonShorten.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o AnonShorten.o `test -f 'src/anonprimitives/AnonShorten.cpp' || echo '$(srcdir)/'`src/anonprimitives/AnonShorten.cpp

AnonShorten.obj: src/anonprimitives/AnonShorten.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT AnonShorten.obj -MD -MP -MF $(DEPDIR)/AnonShorten.Tpo -c -o AnonShorten.obj `if test -f 'src/anonprimitives/AnonShorten.cpp'; then $(CYGPATH_W) 'src/anonprimitives/AnonShorten.cpp'; else $(CYGPATH_W) '$(srcdir)/src/anonprimitives/AnonShorten.cpp'; fi`
	$(am__mv) $(DEPDIR)/AnonShorten.Tpo $(DEPDIR)/AnonShorten.Po
#	source='src/anonprimitives/AnonShorten.cpp' object='AnonShorten.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o AnonShorten.obj `if test -f 'src/anonprimitives/AnonShorten.cpp'; then $(CYGPATH_W) 'src/anonprimitives/AnonShorten.cpp'; else $(CYGPATH_W) '$(srcdir)/src/anonprimitives/AnonShorten.cpp'; fi`

AnonShuffle.o: src/anonprimitives/AnonShuffle.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT AnonShuffle.o -MD -MP -MF $(DEPDIR)/AnonShuffle.Tpo -c -o AnonShuffle.o `test -f 'src/anonprimitives/AnonShuffle.cpp' || echo '$(srcdir)/'`src/anonprimitives/AnonShuffle.cpp
	$(am__mv) $(DEPDIR)/AnonShuffle.Tpo $(DEPDIR)/AnonShuffle.Po
#	source='src/anonprimitives/AnonShuffle.cpp' object='AnonShuffle.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o AnonShuffle.o `test -f 'src/anonprimitives/AnonShuffle.cpp' || echo '$(srcdir)/'`src/anonprimitives/AnonShuffle.cpp

AnonShuffle.obj: src/anonprimitives/AnonShuffle.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT AnonShuffle.obj -MD -MP -MF $(DEPDIR)/AnonShuffle.Tpo -c -o AnonShuffle.obj `if test -f 'src/anonprimitives/AnonShuffle.cpp'; then $(CYGPATH_W) 'src/anonprimitives/AnonShuffle.cpp'; else $(CYGPATH_W) '$(srcdir)/src/anonprimitives/AnonShuffle.cpp'; fi`
	$(am__mv) $(DEPDIR)/AnonShuffle.Tpo $(DEPDIR)/AnonShuffle.Po
#	source='src/anonprimitives/AnonShuffle.cpp' object='AnonShuffle.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o AnonShuffle.obj `if test -f 'src/anonprimitives/AnonShuffle.cpp'; then $(CYGPATH_W) 'src/anonprimitives/AnonShuffle.cpp'; else $(CYGPATH_W) '$(srcdir)/src/anonprimitives/AnonShuffle.cpp'; fi`

AnonWhitenoise.o: src/anonprimitives/AnonWhitenoise.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT AnonWhitenoise.o -MD -MP -MF $(DEPDIR)/AnonWhitenoise.Tpo -c -o AnonWhitenoise.o `test -f 'src/anonprimitives/AnonWhitenoise.cpp' || echo '$(srcdir)/'`src/anonprimitives/AnonWhitenoise.cpp
	$(am__mv) $(DEPDIR)/AnonWhitenoise.Tpo $(DEPDIR)/AnonWhitenoise.Po
#	source='src/anonprimitives/AnonWhitenoise.cpp' object='AnonWhitenoise.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o AnonWhitenoise.o `test -f 'src/anonprimitives/AnonWhitenoise.cpp' || echo '$(srcdir)/'`src/anonprimitives/AnonWhitenoise.cpp

AnonWhitenoise.obj: src/anonprimitives/AnonWhitenoise.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT AnonWhitenoise.obj -MD -MP -MF $(DEPDIR)/AnonWhitenoise.Tpo -c -o AnonWhitenoise.obj `if test -f 'src/anonprimitives/AnonWhitenoise.cpp'; then $(CYGPATH_W) 'src/anonprimitives/AnonWhitenoise.cpp'; else $(CYGPATH_W) '$(srcdir)/src/anonprimitives/AnonWhitenoise.cpp'; fi`
	$(am__mv) $(DEPDIR)/AnonWhitenoise.Tpo $(DEPDIR)/AnonWhitenoise.Po
#	source='src/anonprimitives/AnonWhitenoise.cpp' object='AnonWhitenoise.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o AnonWhitenoise.obj `if test -f 'src/anonprimitives/AnonWhitenoise.cpp'; then $(CYGPATH_W) 'src/anonprimitives/AnonWhitenoise.cpp'; else $(CYGPATH_W) '$(srcdir)/src/anonprimitives/AnonWhitenoise.cpp'; fi`

AnonCryptoPan.o: src/anonprimitives/AnonCryptoPan.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT AnonCryptoPan.o -MD -MP -MF $(DEPDIR)/AnonCryptoPan.Tpo -c -o AnonCryptoPan.o `test -f 'src/anonprimitives/AnonCryptoPan.cpp' || echo '$(srcdir)/'`src/anonprimitives/AnonCryptoPan.cpp
	$(am__mv) $(DEPDIR)/AnonCryptoPan.Tpo $(DEPDIR)/AnonCryptoPan.Po
#	source='src/anonprimitives/AnonCryptoPan.cpp' object='AnonCryptoPan.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o AnonCryptoPan.o `test -f 'src/anonprimitives/AnonCryptoPan.cpp' || echo '$(srcdir)/'`src/anonprimitives/AnonCryptoPan.cpp

AnonCryptoPan.obj: src/anonprimitives/AnonCryptoPan.cpp
	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -MT AnonCryptoPan.obj -MD -MP -MF $(DEPDIR)/AnonCryptoPan.Tpo -c -o AnonCryptoPan.obj `if test -f 'src/anonprimitives/AnonCryptoPan.cpp'; then $(CYGPATH_W) 'src/anonprimitives/AnonCryptoPan.cpp'; else $(CYGPATH_W) '$(srcdir)/src/anonprimitives/AnonCryptoPan.cpp'; fi`
	$(am__mv) $(DEPDIR)/AnonCryptoPan.Tpo $(DEPDIR)/AnonCryptoPan.Po
#	source='src/anonprimitives/AnonCryptoPan.cpp' object='AnonCryptoPan.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS) -c -o AnonCryptoPan.obj `if test -f 'src/anonprimitives/AnonCryptoPan.cpp'; then $(CYGPATH_W) 'src/anonprimitives/AnonCryptoPan.cpp'; else $(CYGPATH_W) '$(srcdir)/src/anonprimitives/AnonCryptoPan.cpp'; fi`

ID: $(HEADERS) $(SOURCES) $(LISP) $(TAGS_FILES)
	list='$(SOURCES) $(HEADERS) $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '{ files[$$0] = 1; nonempty = 1; } \
	      END { if (nonempty) { for (i in files) print i; }; }'`; \
	mkid -fID $$unique
tags: TAGS

TAGS:  $(HEADERS) $(SOURCES)  $(TAGS_DEPENDENCIES) \
		$(TAGS_FILES) $(LISP)
	set x; \
	here=`pwd`; \
	list='$(SOURCES) $(HEADERS)  $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '{ files[$$0] = 1; nonempty = 1; } \
	      END { if (nonempty) { for (i in files) print i; }; }'`; \
	shift; \
	if test -z "$(ETAGS_ARGS)$$*$$unique"; then :; else \
	  test -n "$$unique" || unique=$$empty_fix; \
	  if test $$# -gt 0; then \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      "$$@" $$unique; \
	  else \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      $$unique; \
	  fi; \
	fi
ctags: CTAGS
CTAGS:  $(HEADERS) $(SOURCES)  $(TAGS_DEPENDENCIES) \
		$(TAGS_FILES) $(LISP)
	list='$(SOURCES) $(HEADERS)  $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '{ files[$$0] = 1; nonempty = 1; } \
	      END { if (nonempty) { for (i in files) print i; }; }'`; \
	test -z "$(CTAGS_ARGS)$$unique" \
	  || $(CTAGS) $(CTAGSFLAGS) $(AM_CTAGSFLAGS) $(CTAGS_ARGS) \
	     $$unique

GTAGS:
	here=`$(am__cd) $(top_builddir) && pwd` \
	  && $(am__cd) $(top_srcdir) \
	  && gtags -i $(GTAGS_ARGS) "$$here"

distclean-tags:
	-rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH tags

distdir: $(DISTFILES)
	$(am__remove_distdir)
	test -d "$(distdir)" || mkdir "$(distdir)"
	@srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	topsrcdirstrip=`echo "$(top_srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	list='$(DISTFILES)'; \
	  dist_files=`for file in $$list; do echo $$file; done | \
	  sed -e "s|^$$srcdirstrip/||;t" \
	      -e "s|^$$topsrcdirstrip/|$(top_builddir)/|;t"`; \
	case $$dist_files in \
	  */*) $(MKDIR_P) `echo "$$dist_files" | \
			   sed '/\//!d;s|^|$(distdir)/|;s,/[^/]*$$,,' | \
			   sort -u` ;; \
	esac; \
	for file in $$dist_files; do \
	  if test -f $$file || test -d $$file; then d=.; else d=$(srcdir); fi; \
	  if test -d $$d/$$file; then \
	    dir=`echo "/$$file" | sed -e 's,/[^/]*$$,,'`; \
	    if test -d "$(distdir)/$$file"; then \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    if test -d $(srcdir)/$$file && test $$d != $(srcdir); then \
	      cp -fpR $(srcdir)/$$file "$(distdir)$$dir" || exit 1; \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    cp -fpR $$d/$$file "$(distdir)$$dir" || exit 1; \
	  else \
	    test -f "$(distdir)/$$file" \
	    || cp -p $$d/$$file "$(distdir)/$$file" \
	    || exit 1; \
	  fi; \
	done
	$(MAKE) $(AM_MAKEFLAGS) \
	  top_distdir="$(top_distdir)" distdir="$(distdir)" \
	  dist-hook
	-test -n "$(am__skip_mode_fix)" \
	|| find "$(distdir)" -type d ! -perm -755 \
		-exec chmod u+rwx,go+rx {} \; -o \
	  ! -type d ! -perm -444 -links 1 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -400 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -444 -exec $(install_sh) -c -m a+r {} {} \; \
	|| chmod -R a+r "$(distdir)"
dist-gzip: distdir
	tardir=$(distdir) && $(am__tar) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).tar.gz
	$(am__remove_distdir)

dist-bzip2: distdir
	tardir=$(distdir) && $(am__tar) | bzip2 -9 -c >$(distdir).tar.bz2
	$(am__remove_distdir)

dist-lzma: distdir
	tardir=$(distdir) && $(am__tar) | lzma -9 -c >$(distdir).tar.lzma
	$(am__remove_distdir)

dist-xz: distdir
	tardir=$(distdir) && $(am__tar) | xz -c >$(distdir).tar.xz
	$(am__remove_distdir)

dist-tarZ: distdir
	tardir=$(distdir) && $(am__tar) | compress -c >$(distdir).tar.Z
	$(am__remove_distdir)

dist-shar: distdir
	shar $(distdir) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).shar.gz
	$(am__remove_distdir)

dist-zip: distdir
	-rm -f $(distdir).zip
	zip -rq $(distdir).zip $(distdir)
	$(am__remove_distdir)

dist dist-all: distdir
	tardir=$(distdir) && $(am__tar) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).tar.gz
	$(am__remove_distdir)

# This target untars the dist file and tries a VPATH configuration.  Then
# it guarantees that the distribution is self-contained by making another
# tarfile.
distcheck: dist
	case '$(DIST_ARCHIVES)' in \
	*.tar.gz*) \
	  GZIP=$(GZIP_ENV) gzip -dc $(distdir).tar.gz | $(am__untar) ;;\
	*.tar.bz2*) \
	  bzip2 -dc $(distdir).tar.bz2 | $(am__untar) ;;\
	*.tar.lzma*) \
	  lzma -dc $(distdir).tar.lzma | $(am__untar) ;;\
	*.tar.xz*) \
	  xz -dc $(distdir).tar.xz | $(am__untar) ;;\
	*.tar.Z*) \
	  uncompress -c $(distdir).tar.Z | $(am__untar) ;;\
	*.shar.gz*) \
	  GZIP=$(GZIP_ENV) gzip -dc $(distdir).shar.gz | unshar ;;\
	*.zip*) \
	  unzip $(distdir).zip ;;\
	esac
	chmod -R a-w $(distdir); chmod a+w $(distdir)
	mkdir $(distdir)/_build
	mkdir $(distdir)/_inst
	chmod a-w $(distdir)
	test -d $(distdir)/_build || exit 0; \
	dc_install_base=`$(am__cd) $(distdir)/_inst && pwd | sed -e 's,^[^:\\/]:[\\/],/,'` \
	  && dc_destdir="$${TMPDIR-/tmp}/am-dc-$$$$/" \
	  && am__cwd=`pwd` \
	  && $(am__cd) $(distdir)/_build \
	  && ../configure --srcdir=.. --prefix="$$dc_install_base" \
	    $(DISTCHECK_CONFIGURE_FLAGS) \
	  && $(MAKE) $(AM_MAKEFLAGS) \
	  && $(MAKE) $(AM_MAKEFLAGS) dvi \
	  && $(MAKE) $(AM_MAKEFLAGS) check \
	  && $(MAKE) $(AM_MAKEFLAGS) install \
	  && $(MAKE) $(AM_MAKEFLAGS) installcheck \
	  && $(MAKE) $(AM_MAKEFLAGS) uninstall \
	  && $(MAKE) $(AM_MAKEFLAGS) distuninstallcheck_dir="$$dc_install_base" \
	        distuninstallcheck \
	  && chmod -R a-w "$$dc_install_base" \
	  && ({ \
	       (cd ../.. && umask 077 && mkdir "$$dc_destdir") \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" install \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" uninstall \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" \
	            distuninstallcheck_dir="$$dc_destdir" distuninstallcheck; \
	      } || { rm -rf "$$dc_destdir"; exit 1; }) \
	  && rm -rf "$$dc_destdir" \
	  && $(MAKE) $(AM_MAKEFLAGS) dist \
	  && rm -rf $(DIST_ARCHIVES) \
	  && $(MAKE) $(AM_MAKEFLAGS) distcleancheck \
	  && cd "$$am__cwd" \
	  || exit 1
	$(am__remove_distdir)
	@(echo "$(distdir) archives ready for distribution: "; \
	  list='$(DIST_ARCHIVES)'; for i in $$list; do echo $$i; done) | \
	  sed -e 1h -e 1s/./=/g -e 1p -e 1x -e '$$p' -e '$$x'
distuninstallcheck:
	@$(am__cd) '$(distuninstallcheck_dir)' \
	&& test `$(distuninstallcheck_listfiles) | wc -l` -le 1 \
	   || { echo "ERROR: files left after uninstall:" ; \
	        if test -n "$(DESTDIR)"; then \
	          echo "  (check DESTDIR support)"; \
	        fi ; \
	        $(distuninstallcheck_listfiles) ; \
	        exit 1; } >&2
distcleancheck: distclean
	@if test '$(srcdir)' = . ; then \
	  echo "ERROR: distcleancheck can only run from a VPATH build" ; \
	  exit 1 ; \
	fi
	@test `$(distcleancheck_listfiles) | wc -l` -eq 0 \
	  || { echo "ERROR: files left in build directory after distclean:" ; \
	       $(distcleancheck_listfiles) ; \
	       exit 1; } >&2
check-am: all-am
check: check-am
all-am: Makefile $(PROGRAMS)
installdirs:
	for dir in "$(DESTDIR)$(bindir)"; do \
	  test -z "$$dir" || $(MKDIR_P) "$$dir"; \
	done
install: install-am
install-exec: install-exec-am
install-data: install-data-am
uninstall: uninstall-am

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am

installcheck: installcheck-am
install-strip:
	$(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	  install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	  `test -z '$(STRIP)' || \
	    echo "INSTALL_PROGRAM_ENV=STRIPPROG='$(STRIP)'"` install
mostlyclean-generic:

clean-generic:

distclean-generic:
	-test -z "$(CONFIG_CLEAN_FILES)" || rm -f $(CONFIG_CLEAN_FILES)
	-test . = "$(srcdir)" || test -z "$(CONFIG_CLEAN_VPATH_FILES)" || rm -f $(CONFIG_CLEAN_VPATH_FILES)

maintainer-clean-generic:
	@echo "This command is intended for maintainers to use"
	@echo "it deletes files that may require special tools to rebuild."
clean: clean-am

clean-am: clean-binPROGRAMS clean-generic mostlyclean-am

distclean: distclean-am
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf ./$(DEPDIR)
	-rm -f Makefile
distclean-am: clean-am distclean-compile distclean-generic \
	distclean-tags

dvi: dvi-am

dvi-am:

html: html-am

html-am:

info: info-am

info-am:

install-data-am:

install-dvi: install-dvi-am

install-dvi-am:

install-exec-am: install-binPROGRAMS

install-html: install-html-am

install-html-am:

install-info: install-info-am

install-info-am:

install-man:

install-pdf: install-pdf-am

install-pdf-am:

install-ps: install-ps-am

install-ps-am:

installcheck-am:

maintainer-clean: maintainer-clean-am
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf $(top_srcdir)/autom4te.cache
	-rm -rf ./$(DEPDIR)
	-rm -f Makefile
maintainer-clean-am: distclean-am maintainer-clean-generic

mostlyclean: mostlyclean-am

mostlyclean-am: mostlyclean-compile mostlyclean-generic

pdf: pdf-am

pdf-am:

ps: ps-am

ps-am:

uninstall-am: uninstall-binPROGRAMS

.MAKE: install-am install-strip

.PHONY: CTAGS GTAGS all all-am am--refresh check check-am clean \
	clean-binPROGRAMS clean-generic ctags dist dist-all dist-bzip2 \
	dist-gzip dist-hook dist-lzma dist-shar dist-tarZ dist-xz \
	dist-zip distcheck distclean distclean-compile \
	distclean-generic distclean-tags distcleancheck distdir \
	distuninstallcheck dvi dvi-am html html-am info info-am \
	install install-am install-binPROGRAMS install-data \
	install-data-am install-dvi install-dvi-am install-exec \
	install-exec-am install-html install-html-am install-info \
	install-info-am install-man install-pdf install-pdf-am \
	install-ps install-ps-am install-strip installcheck \
	installcheck-am installdirs maintainer-clean \
	maintainer-clean-generic mostlyclean mostlyclean-compile \
	mostlyclean-generic pdf pdf-am ps ps-am tags uninstall \
	uninstall-am uninstall-binPROGRAMS


# hook to remove all .svn files before rolling the tarball
dist-hook:
	find $(distdir) -name '.[a-zA-Z0-9]*' | xargs rm -rf

# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
